/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "capacidade.h"
#include <syslog.h>

/** Initializes the capacidade module */
void
init_capacidade(void)
{
    const oid capacidade_oid[] = { 1,3,6,1,4,1,12619,1 };

  DEBUGMSGTL(("capacidade", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("capacidade", handle_capacidade,
                               capacidade_oid, OID_LENGTH(capacidade_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_capacidade(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    syslog(LOG_INFO, "1111111111");
    unsigned long cap=0;
    syslog(LOG_INFO, "2222222222");
    switch(reqinfo->mode) {

        case MODE_GET:
			
			
			
            snmp_set_var_typed_value(requests->requestvb, ASN_COUNTER, &cap, sizeof(cap));
            syslog(LOG_INFO, "3333333");
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_capacidade\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
