/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef CAPACIDADE_H
#define CAPACIDADE_H

/* function declarations */
void init_capacidade(void);
Netsnmp_Node_Handler handle_capacidade;

#endif /* CAPACIDADE_H */
