/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "currNumOrders.h"
#include "lib_restaurante.h"

/** Initializes the currNumOrders module */
void
init_currNumOrders(void)
{
    const oid currNumOrders_oid[] = { 1,3,6,1,4,1,12619,10 };

  DEBUGMSGTL(("currNumOrders", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("currNumOrders", handle_currNumOrders,
                               currNumOrders_oid, OID_LENGTH(currNumOrders_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_currNumOrders(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
	FILE *output;
    char app_path[120] = APP_PYTHON_PATH;
    char buffer[BUFF_SIZE];
    unsigned long currOrders;

    switch(reqinfo->mode) {

        case MODE_GET:
            strcat(app_path, "-o");
			syslog(LOG_INFO, "app_path: %s", app_path);
			output = popen (app_path, "r"); // Call the restaurante app, and parse the ouput
			if (!output)
			{
				syslog (LOG_INFO,"incorrect parameters or too many files.\n");
				return EXIT_FAILURE;
			}
			fgets(buffer, BUFF_SIZE, output);
			currOrders = strtoul(buffer, NULL, 10);
			pclose(output);
		
            snmp_set_var_typed_value(requests->requestvb, ASN_COUNTER, &currOrders, sizeof(currOrders));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_currNumOrders\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
