/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef CURRNUMORDERS_H
#define CURRNUMORDERS_H

/* function declarations */
void init_currNumOrders(void);
Netsnmp_Node_Handler handle_currNumOrders;

#endif /* CURRNUMORDERS_H */
