/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
#ifndef DAILYORDERSTABLE_H
#define DAILYORDERSTABLE_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup misc misc: Miscellaneous routines
 *
 * @{
 */
#include <net-snmp/library/asn1.h>

/* other required module components */
    /* *INDENT-OFF*  */
config_add_mib(RestCtrl-MIB)
config_require(RestCtrl-MIB/dailyOrdersTable/dailyOrdersTable_interface)
config_require(RestCtrl-MIB/dailyOrdersTable/dailyOrdersTable_data_access)
config_require(RestCtrl-MIB/dailyOrdersTable/dailyOrdersTable_data_get)
config_require(RestCtrl-MIB/dailyOrdersTable/dailyOrdersTable_data_set)
    /* *INDENT-ON*  */

/* OID and column number definitions for dailyOrdersTable */
#include "dailyOrdersTable_oids.h"

/* enum definions */
#include "dailyOrdersTable_enums.h"

/* *********************************************************************
 * function declarations
 */
void init_dailyOrdersTable(void);
void shutdown_dailyOrdersTable(void);

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dailyOrdersTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RestCtrl-MIB::dailyOrdersTable is subid 8 of restCtrl.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.12619.8, length: 8
*/
/* *********************************************************************
 * When you register your mib, you get to provide a generic
 * pointer that will be passed back to you for most of the
 * functions calls.
 *
 * TODO:100:r: Review all context structures
 */
    /*
     * TODO:101:o: |-> Review dailyOrdersTable registration context.
     */
typedef netsnmp_data_list dailyOrdersTable_registration;

/**********************************************************************/
/*
 * TODO:110:r: |-> Review dailyOrdersTable data context structure.
 * This structure is used to represent the data for dailyOrdersTable.
 */
/*
 * This structure contains storage for all the columns defined in the
 * dailyOrdersTable.
 */
typedef struct dailyOrdersTable_data_s {
    
        /*
         * year(2)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/R/d/h
         */
   long   year;
    
        /*
         * month(3)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/R/d/h
         */
   long   month;
    
        /*
         * day(4)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/R/d/h
         */
   long   day;
    
        /*
         * orders(5)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/R/d/h
         */
   long   orders;
    
} dailyOrdersTable_data;


/*
 * TODO:120:r: |-> Review dailyOrdersTable mib index.
 * This structure is used to represent the index for dailyOrdersTable.
 */
typedef struct dailyOrdersTable_mib_index_s {

        /*
         * dailyOrdersIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/R/d/h
         */
   long   dailyOrdersIndex;


} dailyOrdersTable_mib_index;

    /*
     * TODO:121:r: |   |-> Review dailyOrdersTable max index length.
     * If you KNOW that your indexes will never exceed a certain
     * length, update this macro to that length.
*/
#define MAX_dailyOrdersTable_IDX_LEN     1


/* *********************************************************************
 * TODO:130:o: |-> Review dailyOrdersTable Row request (rowreq) context.
 * When your functions are called, you will be passed a
 * dailyOrdersTable_rowreq_ctx pointer.
 */
typedef struct dailyOrdersTable_rowreq_ctx_s {

    /** this must be first for container compare to work */
    netsnmp_index        oid_idx;
    oid                  oid_tmp[MAX_dailyOrdersTable_IDX_LEN];
    
    dailyOrdersTable_mib_index        tbl_idx;
    
    dailyOrdersTable_data              data;

    /*
     * flags per row. Currently, the first (lower) 8 bits are reserved
     * for the user. See mfd.h for other flags.
     */
    u_int                       rowreq_flags;

    /*
     * TODO:131:o: |   |-> Add useful data to dailyOrdersTable rowreq context.
     */
    
    /*
     * storage for future expansion
     */
    netsnmp_data_list             *dailyOrdersTable_data_list;

} dailyOrdersTable_rowreq_ctx;

typedef struct dailyOrdersTable_ref_rowreq_ctx_s {
    dailyOrdersTable_rowreq_ctx *rowreq_ctx;
} dailyOrdersTable_ref_rowreq_ctx;

/* *********************************************************************
 * function prototypes
 */
    int dailyOrdersTable_pre_request(dailyOrdersTable_registration * user_context);
    int dailyOrdersTable_post_request(dailyOrdersTable_registration * user_context,
        int rc);

    int dailyOrdersTable_rowreq_ctx_init(dailyOrdersTable_rowreq_ctx *rowreq_ctx,
                                   void *user_init_ctx);
    void dailyOrdersTable_rowreq_ctx_cleanup(dailyOrdersTable_rowreq_ctx *rowreq_ctx);


    dailyOrdersTable_rowreq_ctx *
                  dailyOrdersTable_row_find_by_mib_index(dailyOrdersTable_mib_index *mib_idx);

extern const oid dailyOrdersTable_oid[];
extern const int dailyOrdersTable_oid_size;


#include "dailyOrdersTable_interface.h"
#include "dailyOrdersTable_data_access.h"
#include "dailyOrdersTable_data_get.h"
#include "dailyOrdersTable_data_set.h"

/*
 * DUMMY markers, ignore
 *
 * TODO:099:x: *************************************************************
 * TODO:199:x: *************************************************************
 * TODO:299:x: *************************************************************
 * TODO:399:x: *************************************************************
 * TODO:499:x: *************************************************************
 */

#ifdef __cplusplus
}
#endif

#endif /* DAILYORDERSTABLE_H */
/** @} */
