/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
#ifndef DAILYORDERSTABLE_DATA_ACCESS_H
#define DAILYORDERSTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dailyOrdersTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RestCtrl-MIB::dailyOrdersTable is subid 8 of restCtrl.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.12619.8, length: 8
*/


    int dailyOrdersTable_init_data(dailyOrdersTable_registration * dailyOrdersTable_reg);


    /*
     * TODO:180:o: Review dailyOrdersTable cache timeout.
     * The number of seconds before the cache times out
     */
#define DAILYORDERSTABLE_CACHE_TIMEOUT   60

void dailyOrdersTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
void dailyOrdersTable_container_shutdown(netsnmp_container *container_ptr);

int dailyOrdersTable_container_load(netsnmp_container *container);
void dailyOrdersTable_container_free(netsnmp_container *container);

int dailyOrdersTable_cache_load(netsnmp_container *container);
void dailyOrdersTable_cache_free(netsnmp_container *container);

    int dailyOrdersTable_row_prep( dailyOrdersTable_rowreq_ctx *rowreq_ctx);



#ifdef __cplusplus
}
#endif

#endif /* DAILYORDERSTABLE_DATA_ACCESS_H */
