/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
/** \page MFD helper for dailyOrdersTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "dailyOrdersTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "dailyOrdersTable_interface.h"

const oid dailyOrdersTable_oid[] = { DAILYORDERSTABLE_OID };
const int dailyOrdersTable_oid_size = OID_LENGTH(dailyOrdersTable_oid);

    dailyOrdersTable_registration  dailyOrdersTable_user_context;

void initialize_table_dailyOrdersTable(void);
void shutdown_table_dailyOrdersTable(void);


/**
 * Initializes the dailyOrdersTable module
 */
void
init_dailyOrdersTable(void)
{
    DEBUGMSGTL(("verbose:dailyOrdersTable:init_dailyOrdersTable","called\n"));

    /*
     * TODO:300:o: Perform dailyOrdersTable one-time module initialization.
     */
     
    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("dailyOrdersTable"))
        initialize_table_dailyOrdersTable();

} /* init_dailyOrdersTable */

/**
 * Shut-down the dailyOrdersTable module (agent is exiting)
 */
void
shutdown_dailyOrdersTable(void)
{
    if (should_init("dailyOrdersTable"))
        shutdown_table_dailyOrdersTable();

}

/**
 * Initialize the table dailyOrdersTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_dailyOrdersTable(void)
{
    dailyOrdersTable_registration * user_context;
    u_long flags;

    DEBUGMSGTL(("verbose:dailyOrdersTable:initialize_table_dailyOrdersTable","called\n"));

    /*
     * TODO:301:o: Perform dailyOrdersTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize dailyOrdersTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context = netsnmp_create_data_list("dailyOrdersTable", NULL, NULL);
    
    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;
    
    /*
     * call interface initialization code
     */
    _dailyOrdersTable_initialize_interface(user_context, flags);
} /* initialize_table_dailyOrdersTable */

/**
 * Shutdown the table dailyOrdersTable 
 */
void
shutdown_table_dailyOrdersTable(void)
{
    /*
     * call interface shutdown code
     */
    _dailyOrdersTable_shutdown_interface(&dailyOrdersTable_user_context);
}

/**
 * extra context initialization (eg default values)
 *
 * @param rowreq_ctx    : row request context
 * @param user_init_ctx : void pointer for user (parameter to rowreq_ctx_allocate)
 *
 * @retval MFD_SUCCESS  : no errors
 * @retval MFD_ERROR    : error (context allocate will fail)
 */
int
dailyOrdersTable_rowreq_ctx_init(dailyOrdersTable_rowreq_ctx *rowreq_ctx,
                           void *user_init_ctx)
{
    DEBUGMSGTL(("verbose:dailyOrdersTable:dailyOrdersTable_rowreq_ctx_init","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:210:o: |-> Perform extra dailyOrdersTable rowreq initialization. (eg DEFVALS)
     */

    return MFD_SUCCESS;
} /* dailyOrdersTable_rowreq_ctx_init */

/**
 * extra context cleanup
 *
 */
void dailyOrdersTable_rowreq_ctx_cleanup(dailyOrdersTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:dailyOrdersTable:dailyOrdersTable_rowreq_ctx_cleanup","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:211:o: |-> Perform extra dailyOrdersTable rowreq cleanup.
     */
} /* dailyOrdersTable_rowreq_ctx_cleanup */

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
dailyOrdersTable_pre_request(dailyOrdersTable_registration * user_context)
{
    DEBUGMSGTL(("verbose:dailyOrdersTable:dailyOrdersTable_pre_request","called\n"));

    /*
     * TODO:510:o: Perform dailyOrdersTable pre-request actions.
     */

    return MFD_SUCCESS;
} /* dailyOrdersTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
dailyOrdersTable_post_request(dailyOrdersTable_registration * user_context, int rc)
{
    DEBUGMSGTL(("verbose:dailyOrdersTable:dailyOrdersTable_post_request","called\n"));

    /*
     * TODO:511:o: Perform dailyOrdersTable post-request actions.
     */

    return MFD_SUCCESS;
} /* dailyOrdersTable_post_request */


/** @{ */
