/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 *
 * $Id:$
 */
#ifndef DAILYORDERSTABLE_OIDS_H
#define DAILYORDERSTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table dailyOrdersTable */
#define DAILYORDERSTABLE_OID              1,3,6,1,4,1,12619,8


#define COLUMN_DAILYORDERSINDEX         1
    
#define COLUMN_YEAR         2
    
#define COLUMN_MONTH         3
    
#define COLUMN_DAY         4
    
#define COLUMN_ORDERS         5
    

#define DAILYORDERSTABLE_MIN_COL   COLUMN_DAILYORDERSINDEX
#define DAILYORDERSTABLE_MAX_COL   COLUMN_ORDERS
    


#ifdef __cplusplus
}
#endif

#endif /* DAILYORDERSTABLE_OIDS_H */
