/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef ESTOQUETRAP_H
#define ESTOQUETRAP_H

/* function declarations */
int send_estoqueItemChange_trap(long estoqueIndex, char* name, unsigned long amount);

#endif /* ESTOQUETRAP_H */
