/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 *
 * @file estoqueTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef ESTOQUETABLE_DATA_GET_H
#define ESTOQUETABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table estoqueTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RestCtrl-MIB::estoqueTable is subid 9 of restCtrl.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.12619.9, length: 8
*/
    /*
     * indexes
     */

    int name_get( estoqueTable_rowreq_ctx *rowreq_ctx, char **name_val_ptr_ptr, size_t *name_val_ptr_len_ptr );
    int amount_get( estoqueTable_rowreq_ctx *rowreq_ctx, long * amount_val_ptr );


int estoqueTable_indexes_set_tbl_idx(estoqueTable_mib_index *tbl_idx, long estoqueIndex_val);
int estoqueTable_indexes_set(estoqueTable_rowreq_ctx *rowreq_ctx, long estoqueIndex_val);




#ifdef __cplusplus
}
#endif

#endif /* ESTOQUETABLE_DATA_GET_H */
/** @} */
