/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */

/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "estoqueTable.h"


#include <net-snmp/agent/table_container.h>
#include <net-snmp/library/container.h>

#include "estoqueTable_interface.h"

netsnmp_feature_require(baby_steps)
netsnmp_feature_require(row_merge)
netsnmp_feature_require(check_all_requests_error)

#include <ctype.h>

/**********************************************************************
 **********************************************************************
 ***
 *** Table estoqueTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RestCtrl-MIB::estoqueTable is subid 9 of restCtrl.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.12619.9, length: 8
*/
typedef struct estoqueTable_interface_ctx_s {

   netsnmp_container              *container;
   netsnmp_cache                  *cache;

   estoqueTable_registration *      user_ctx;
   
   netsnmp_table_registration_info  tbl_info;

   netsnmp_baby_steps_access_methods access_multiplexer;

    u_int                             table_dirty;

} estoqueTable_interface_ctx;

static estoqueTable_interface_ctx estoqueTable_if_ctx;

static void _estoqueTable_container_init(
    estoqueTable_interface_ctx *if_ctx);
static void _estoqueTable_container_shutdown(
    estoqueTable_interface_ctx *if_ctx);


netsnmp_container *
estoqueTable_container_get( void )
{
    return estoqueTable_if_ctx.container;
}

estoqueTable_registration *
estoqueTable_registration_get( void )
{
    return estoqueTable_if_ctx.user_ctx;
}

estoqueTable_registration *
estoqueTable_registration_set( estoqueTable_registration * newreg )
{
    estoqueTable_registration * old = estoqueTable_if_ctx.user_ctx;
    estoqueTable_if_ctx.user_ctx = newreg;
    return old;
}

int
estoqueTable_container_size( void )
{
    return CONTAINER_SIZE(estoqueTable_if_ctx.container);
}

u_int
estoqueTable_dirty_get( void )
{
    return estoqueTable_if_ctx.table_dirty;
}

void
estoqueTable_dirty_set( u_int status )
{
    DEBUGMSGTL(("estoqueTable:estoqueTable_dirty_set",
                "called. was %d, now %d\n",
                estoqueTable_if_ctx.table_dirty, status));
    estoqueTable_if_ctx.table_dirty = status;
}

/*
 * mfd multiplexer modes
 */
static Netsnmp_Node_Handler _mfd_estoqueTable_pre_request;
static Netsnmp_Node_Handler _mfd_estoqueTable_post_request;
static Netsnmp_Node_Handler _mfd_estoqueTable_object_lookup;
static Netsnmp_Node_Handler _mfd_estoqueTable_get_values;
static Netsnmp_Node_Handler _mfd_estoqueTable_check_objects;
static Netsnmp_Node_Handler _mfd_estoqueTable_undo_setup;
static Netsnmp_Node_Handler _mfd_estoqueTable_set_values;
static Netsnmp_Node_Handler _mfd_estoqueTable_undo_cleanup;
static Netsnmp_Node_Handler _mfd_estoqueTable_undo_values;
static Netsnmp_Node_Handler _mfd_estoqueTable_commit;
static Netsnmp_Node_Handler _mfd_estoqueTable_undo_commit;
static Netsnmp_Node_Handler _mfd_estoqueTable_irreversible_commit;

estoqueTable_data *estoqueTable_allocate_data(void);

/**
 * @internal
 * Initialize the table estoqueTable 
 *    (Define its contents and how it's structured)
 */
void
_estoqueTable_initialize_interface(estoqueTable_registration * reg_ptr,  u_long flags)
{
    netsnmp_baby_steps_access_methods *access_multiplexer =
        &estoqueTable_if_ctx.access_multiplexer;
    netsnmp_table_registration_info *tbl_info = &estoqueTable_if_ctx.tbl_info;
    netsnmp_handler_registration *reginfo;
    netsnmp_mib_handler *handler;
    int    mfd_modes = 0;

    DEBUGMSGTL(("internal:estoqueTable:_estoqueTable_initialize_interface","called\n"));


    /*************************************************
     *
     * save interface context for estoqueTable
     */
    /*
     * Setting up the table's definition
     */
    netsnmp_table_helper_add_indexes(tbl_info,
                                  ASN_INTEGER, /** index: estoqueIndex */
                             0);

    /*  Define the minimum and maximum accessible columns.  This
        optimizes retrieval. */
    tbl_info->min_column = ESTOQUETABLE_MIN_COL;
    tbl_info->max_column = ESTOQUETABLE_MAX_COL;

    /*
     * save users context
     */
    estoqueTable_if_ctx.user_ctx = reg_ptr;

    /*
     * call data access initialization code
     */
    estoqueTable_init_data(reg_ptr);

    /*
     * set up the container
     */
    _estoqueTable_container_init(&estoqueTable_if_ctx);
    if (NULL == estoqueTable_if_ctx.container) {
        snmp_log(LOG_ERR,"could not initialize container for estoqueTable\n");
        return;
    }
    
    /*
     * access_multiplexer: REQUIRED wrapper for get request handling
     */
    access_multiplexer->object_lookup = _mfd_estoqueTable_object_lookup;
    access_multiplexer->get_values = _mfd_estoqueTable_get_values;

    /*
     * no wrappers yet
     */
    access_multiplexer->pre_request = _mfd_estoqueTable_pre_request;
    access_multiplexer->post_request = _mfd_estoqueTable_post_request;

#ifndef NETSNMP_DISABLE_SET_SUPPORT

    /*
     * REQUIRED wrappers for set request handling
     */
    access_multiplexer->object_syntax_checks = _mfd_estoqueTable_check_objects;
    access_multiplexer->undo_setup = _mfd_estoqueTable_undo_setup;
    access_multiplexer->undo_cleanup = _mfd_estoqueTable_undo_cleanup;
    access_multiplexer->set_values = _mfd_estoqueTable_set_values;
    access_multiplexer->undo_sets = _mfd_estoqueTable_undo_values;

    /*
     * no wrappers yet
     */
    access_multiplexer->commit = _mfd_estoqueTable_commit;
    access_multiplexer->undo_commit = _mfd_estoqueTable_undo_commit;
    access_multiplexer->irreversible_commit = _mfd_estoqueTable_irreversible_commit;
#endif

    /*************************************************
     *
     * Create a registration, save our reg data, register table.
     */
    DEBUGMSGTL(("estoqueTable:init_estoqueTable",
                "Registering estoqueTable as a mibs-for-dummies table.\n"));		 
    handler = netsnmp_baby_steps_access_multiplexer_get(access_multiplexer);
    reginfo = netsnmp_handler_registration_create("estoqueTable", handler,
                                                  estoqueTable_oid,
                                                  estoqueTable_oid_size,
                                                  HANDLER_CAN_BABY_STEP |
#if !(defined(NETSNMP_NO_WRITE_SUPPORT) || defined(NETSNMP_DISABLE_SET_SUPPORT))
                                                  HANDLER_CAN_RONLY
#else
                                                  HANDLER_CAN_RWRITE
#endif /* NETSNMP_NO_WRITE_SUPPORT || NETSNMP_DISABLE_SET_SUPPORT */
                                                  );
    if(NULL == reginfo) {
        snmp_log(LOG_ERR,"error registering table estoqueTable\n");
        return;
    }
    reginfo->my_reg_void = &estoqueTable_if_ctx;

    /*************************************************
     *
     * set up baby steps handler, create it and inject it
     */
    if( access_multiplexer->object_lookup )
        mfd_modes |= BABY_STEP_OBJECT_LOOKUP;
    if( access_multiplexer->pre_request )
        mfd_modes |= BABY_STEP_PRE_REQUEST;
    if( access_multiplexer->post_request )
        mfd_modes |= BABY_STEP_POST_REQUEST;
    
#if !(defined(NETSNMP_NO_WRITE_SUPPORT) || defined(NETSNMP_DISABLE_SET_SUPPORT))
    if( access_multiplexer->set_values )
        mfd_modes |= BABY_STEP_SET_VALUES;
    if( access_multiplexer->irreversible_commit )
        mfd_modes |= BABY_STEP_IRREVERSIBLE_COMMIT;
    if( access_multiplexer->object_syntax_checks )
        mfd_modes |= BABY_STEP_CHECK_OBJECT;

    if( access_multiplexer->undo_setup )
        mfd_modes |= BABY_STEP_UNDO_SETUP;
    if( access_multiplexer->undo_cleanup )
        mfd_modes |= BABY_STEP_UNDO_CLEANUP;
    if( access_multiplexer->undo_sets )
        mfd_modes |= BABY_STEP_UNDO_SETS;
    
    if( access_multiplexer->row_creation )
        mfd_modes |= BABY_STEP_ROW_CREATE;
    if( access_multiplexer->consistency_checks )
        mfd_modes |= BABY_STEP_CHECK_CONSISTENCY;
    if( access_multiplexer->commit )
        mfd_modes |= BABY_STEP_COMMIT;
    if( access_multiplexer->undo_commit )
        mfd_modes |= BABY_STEP_UNDO_COMMIT;
#endif /* NETSNMP_NO_WRITE_SUPPORT || NETSNMP_DISABLE_SET_SUPPORT */
    
    handler = netsnmp_baby_steps_handler_get(mfd_modes);
    netsnmp_inject_handler(reginfo, handler);

    /*************************************************
     *
     * inject row_merge helper with prefix rootoid_len + 2 (entry.col)
     */
    handler = netsnmp_get_row_merge_handler(reginfo->rootoid_len + 2);
    netsnmp_inject_handler(reginfo, handler);

    /*************************************************
     *
     * inject container_table helper
     */
    handler =
        netsnmp_container_table_handler_get(tbl_info,
                                            estoqueTable_if_ctx.container,
                                            TABLE_CONTAINER_KEY_NETSNMP_INDEX);
    netsnmp_inject_handler( reginfo, handler );

    /*************************************************
     *
     * inject cache helper
     */
    if(NULL != estoqueTable_if_ctx.cache) {
        handler = netsnmp_cache_handler_get(estoqueTable_if_ctx.cache);
        netsnmp_inject_handler( reginfo, handler );
    }

    /*
     * register table
     */
    netsnmp_register_table(reginfo, tbl_info);

} /* _estoqueTable_initialize_interface */

/**
 * @internal
 * Shutdown the table estoqueTable
 */
void
_estoqueTable_shutdown_interface(estoqueTable_registration * reg_ptr)
{
    /*
     * shutdown the container
     */
    _estoqueTable_container_shutdown(&estoqueTable_if_ctx);
}

void
estoqueTable_valid_columns_set(netsnmp_column_info *vc)
{
    estoqueTable_if_ctx.tbl_info.valid_columns = vc;
} /* estoqueTable_valid_columns_set */

/**
 * @internal
 * convert the index component stored in the context to an oid
 */
int
estoqueTable_index_to_oid(netsnmp_index *oid_idx,
                         estoqueTable_mib_index *mib_idx)
{
    int err = SNMP_ERR_NOERROR;
    
    /*
     * temp storage for parsing indexes
     */
    /*
     * estoqueIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/d/h
     */
    netsnmp_variable_list var_estoqueIndex;

    /*
     * set up varbinds
     */
    memset( &var_estoqueIndex, 0x00, sizeof(var_estoqueIndex) );
    var_estoqueIndex.type = ASN_INTEGER;

    /*
     * chain temp index varbinds together
     */
    var_estoqueIndex.next_variable =  NULL;


    DEBUGMSGTL(("verbose:estoqueTable:estoqueTable_index_to_oid","called\n"));

        /* estoqueIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/d/h */
    snmp_set_var_value(&var_estoqueIndex, &mib_idx->estoqueIndex, sizeof(mib_idx->estoqueIndex));


    err = build_oid_noalloc(oid_idx->oids, oid_idx->len, &oid_idx->len,
                           NULL, 0, &var_estoqueIndex);
    if(err)
        snmp_log(LOG_ERR,"error %d converting index to oid\n", err);

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers( &var_estoqueIndex );

    return err;
} /* estoqueTable_index_to_oid */

/**
 * extract estoqueTable indexes from a netsnmp_index
 *
 * @retval SNMP_ERR_NOERROR  : no error
 * @retval SNMP_ERR_GENERR   : error
 */
int
estoqueTable_index_from_oid(netsnmp_index *oid_idx,
                         estoqueTable_mib_index *mib_idx)
{
    int err = SNMP_ERR_NOERROR;
    
    /*
     * temp storage for parsing indexes
     */
    /*
     * estoqueIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/d/h
     */
    netsnmp_variable_list var_estoqueIndex;

    /*
     * set up varbinds
     */
    memset( &var_estoqueIndex, 0x00, sizeof(var_estoqueIndex) );
    var_estoqueIndex.type = ASN_INTEGER;

    /*
     * chain temp index varbinds together
     */
    var_estoqueIndex.next_variable =  NULL;


    DEBUGMSGTL(("verbose:estoqueTable:estoqueTable_index_from_oid","called\n"));

    /*
     * parse the oid into the individual index components
     */
    err = parse_oid_indexes( oid_idx->oids, oid_idx->len,
                             &var_estoqueIndex );
    if (err == SNMP_ERR_NOERROR) {
        /*
         * copy out values
         */
    mib_idx->estoqueIndex = *((long *)var_estoqueIndex.val.string);


    }

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers( &var_estoqueIndex );

    return err;
} /* estoqueTable_index_from_oid */


/*
 * estoqueTable_allocate_data
 *
 * Purpose: create new estoqueTable_data.
 */
estoqueTable_data *
estoqueTable_allocate_data(void)
{
    estoqueTable_data *rtn = SNMP_MALLOC_TYPEDEF(estoqueTable_data);

    DEBUGMSGTL(("verbose:estoqueTable:estoqueTable_allocate_data","called\n"));

    if(NULL == rtn) {
        snmp_log(LOG_ERR, "unable to malloc memory for new "
                 "estoqueTable_data.\n");
    }

    return rtn;
} /* estoqueTable_allocate_data */

/*
 * estoqueTable_release_data
 *
 * Purpose: release estoqueTable data.
 */
void
estoqueTable_release_data(estoqueTable_data *data)
{
    DEBUGMSGTL(("verbose:estoqueTable:estoqueTable_release_data","called\n"));

    free(data);
} /* estoqueTable_release_data */

/* *********************************************************************
 * @internal
 * allocate resources for a estoqueTable_rowreq_ctx
 */
estoqueTable_rowreq_ctx *
estoqueTable_allocate_rowreq_ctx(void *user_init_ctx)
{
    estoqueTable_rowreq_ctx *rowreq_ctx =
                  SNMP_MALLOC_TYPEDEF(estoqueTable_rowreq_ctx);

    DEBUGMSGTL(("internal:estoqueTable:estoqueTable_allocate_rowreq_ctx","called\n"));

    if(NULL == rowreq_ctx) {
        snmp_log(LOG_ERR,"Couldn't allocate memory for a "
                 "estoqueTable_rowreq_ctx.\n");
        return NULL;
    }

    rowreq_ctx->oid_idx.oids = rowreq_ctx->oid_tmp;

    rowreq_ctx->estoqueTable_data_list = NULL;

    /*
     * if we allocated data, call init routine
     */
    if (!(rowreq_ctx->rowreq_flags & MFD_ROW_DATA_FROM_USER)) {
        if(SNMPERR_SUCCESS !=
            estoqueTable_rowreq_ctx_init(rowreq_ctx, user_init_ctx)) {
           estoqueTable_release_rowreq_ctx(rowreq_ctx);
           rowreq_ctx = NULL;
        }
    }

    return rowreq_ctx;
} /* estoqueTable_allocate_rowreq_ctx */

/*
 * @internal
 * release resources for a estoqueTable_rowreq_ctx
 */
void
estoqueTable_release_rowreq_ctx(estoqueTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("internal:estoqueTable:estoqueTable_release_rowreq_ctx","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    estoqueTable_rowreq_ctx_cleanup(rowreq_ctx);

    if(rowreq_ctx->undo)
        estoqueTable_release_data(rowreq_ctx->undo);
 
    /*
     * free index oid pointer
     */
    if(rowreq_ctx->oid_idx.oids != rowreq_ctx->oid_tmp)
        free(rowreq_ctx->oid_idx.oids);

    SNMP_FREE(rowreq_ctx);
} /* estoqueTable_release_rowreq_ctx */

/**
 * @internal
 * wrapper
 */
static int
_mfd_estoqueTable_pre_request(netsnmp_mib_handler *handler,
                            netsnmp_handler_registration *reginfo,
                            netsnmp_agent_request_info *agtreq_info,
                            netsnmp_request_info *requests)
{
    int rc;

    DEBUGMSGTL(("internal:estoqueTable:_mfd_estoqueTable_pre_request",
                "called\n"));
    
    if (1 != netsnmp_row_merge_status_first(reginfo, agtreq_info)) {
        DEBUGMSGTL(("internal:estoqueTable",
                    "skipping additional pre_request\n"));
        return SNMP_ERR_NOERROR;
    }
        
    rc = estoqueTable_pre_request(estoqueTable_if_ctx.user_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("estoqueTable","error %d from "
                    "estoqueTable_pre_request\n", rc));
        netsnmp_request_set_error_all(requests, SNMP_VALIDATE_ERR(rc));
    }
    
    return SNMP_ERR_NOERROR;
} /* _mfd_estoqueTable_pre_request */

/**
 * @internal
 * wrapper
 */
static int
_mfd_estoqueTable_post_request(netsnmp_mib_handler *handler,
                             netsnmp_handler_registration *reginfo,
                             netsnmp_agent_request_info *agtreq_info,
                             netsnmp_request_info *requests)
{
    estoqueTable_rowreq_ctx *rowreq_ctx = (estoqueTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    int rc, packet_rc;

    DEBUGMSGTL(("internal:estoqueTable:_mfd_estoqueTable_post_request",
                "called\n"));

    /*
     * release row context, if deleted
     */
    if (rowreq_ctx && (rowreq_ctx->rowreq_flags & MFD_ROW_DELETED))
        estoqueTable_release_rowreq_ctx(rowreq_ctx);

    /*
     * wait for last call before calling user
     */
    if (1 != netsnmp_row_merge_status_last(reginfo, agtreq_info)) {
        DEBUGMSGTL(("internal:estoqueTable",
                    "waiting for last post_request\n"));
        return SNMP_ERR_NOERROR;
    }
    
    packet_rc = netsnmp_check_all_requests_error(agtreq_info->asp, 0);
    if ((MFD_SUCCESS != packet_rc) && estoqueTable_dirty_get()) {
        /*
         * we shouldn't get here. the undo steps should also clear
         * the dirty flags.
         */
        snmp_log(LOG_WARNING, "estoqueTable dirty flag set in post_request "
                 "but status != SUCCESS.\n");
    }

    rc = estoqueTable_post_request(estoqueTable_if_ctx.user_ctx,packet_rc);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("estoqueTable","error %d from "
                    "estoqueTable_post_request\n", rc));
    }
    
    return SNMP_ERR_NOERROR;
} /* _mfd_estoqueTable_post_request */

/**
 * @internal
 * wrapper
 */
static int
_mfd_estoqueTable_object_lookup(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc = SNMP_ERR_NOERROR;
    estoqueTable_rowreq_ctx *rowreq_ctx = (estoqueTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    
    DEBUGMSGTL(("internal:estoqueTable:_mfd_estoqueTable_object_lookup","called\n"));

    /*
     * get our context from mfd
     * estoqueTable_interface_ctx *if_ctx =
     *             (estoqueTable_interface_ctx *)reginfo->my_reg_void;
     */

    if(NULL == rowreq_ctx) {
        rc = SNMP_ERR_NOCREATION;
    }

    if (MFD_SUCCESS != rc)
        netsnmp_request_set_error_all(requests, rc);
    else
        estoqueTable_row_prep(rowreq_ctx);

    return SNMP_VALIDATE_ERR(rc);
} /* _mfd_estoqueTable_object_lookup */

/***********************************************************************
 *
 * GET processing
 *
 ***********************************************************************/
/*
 * @internal
 * Retrieve the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_estoqueTable_get_column( estoqueTable_rowreq_ctx *rowreq_ctx,
                       netsnmp_variable_list *var, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:estoqueTable:_mfd_estoqueTable_get_column",
                "called for %d\n", column));


    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {

    /* (INDEX) estoqueIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/d/h */
    case COLUMN_ESTOQUEINDEX:
    var->type = ASN_INTEGER;
        var->val_len = sizeof(long);
        (*var->val.integer) = rowreq_ctx->tbl_idx.estoqueIndex;
        break;

    /* name(2)/DisplayString/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/H */
    case COLUMN_NAME:
    var->type = ASN_OCTET_STR;
rc = name_get(rowreq_ctx, (char **)&var->val.string, &var->val_len );
        break;

    /* amount(3)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/d/h */
    case COLUMN_AMOUNT:
    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = amount_get(rowreq_ctx, (long *)var->val.string );
        break;

     default:
        if (ESTOQUETABLE_MIN_COL <= column && column <= ESTOQUETABLE_MAX_COL) {
            DEBUGMSGTL(("internal:estoqueTable:_mfd_estoqueTable_get_column",
                "assume column %d is reserved\n", column));
            rc = MFD_SKIP;
        } else {
            snmp_log(LOG_ERR,
                "unknown column %d in _estoqueTable_get_column\n", column);
        }
        break;
    }

    return rc;
} /* _estoqueTable_get_column */

int
_mfd_estoqueTable_get_values(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    estoqueTable_rowreq_ctx *rowreq_ctx = (estoqueTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info * tri;
    u_char                     * old_string;
    void                      (*dataFreeHook)(void *);
    int                        rc;

    DEBUGMSGTL(("internal:estoqueTable:_mfd_estoqueTable_get_values","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    for(;requests; requests = requests->next) {
        /*
         * save old pointer, so we can free it if replaced
         */
        old_string = requests->requestvb->val.string;
        dataFreeHook = requests->requestvb->dataFreeHook;
        if(NULL == requests->requestvb->val.string) {
            requests->requestvb->val.string = requests->requestvb->buf;
            requests->requestvb->val_len = sizeof(requests->requestvb->buf);
        }
        else if(requests->requestvb->buf == requests->requestvb->val.string) {
            if(requests->requestvb->val_len != sizeof(requests->requestvb->buf))
                requests->requestvb->val_len = sizeof(requests->requestvb->buf);
        }

        /*
         * get column data
         */
        tri = netsnmp_extract_table_info(requests);
        if(NULL == tri)
            continue;
        
        rc = _estoqueTable_get_column(rowreq_ctx, requests->requestvb, tri->colnum);
        if(rc) {
            if(MFD_SKIP == rc) {
                requests->requestvb->type = SNMP_NOSUCHINSTANCE;
                rc = SNMP_ERR_NOERROR;
            }
        }
        else if (NULL == requests->requestvb->val.string) {
            snmp_log(LOG_ERR,"NULL varbind data pointer!\n");
            rc = SNMP_ERR_GENERR;
        }
        if(rc)
            netsnmp_request_set_error(requests, SNMP_VALIDATE_ERR(rc));

        /*
         * if the buffer wasn't used previously for the old data (i.e. it
         * was allcoated memory)  and the get routine replaced the pointer,
         * we need to free the previous pointer.
         */
        if(old_string && (old_string != requests->requestvb->buf) &&
           (requests->requestvb->val.string != old_string)) {
            if(dataFreeHook)
                (*dataFreeHook)(old_string);
            else
                free(old_string);
        }
    } /* for results */

    return SNMP_ERR_NOERROR;
} /* _mfd_estoqueTable_get_values */

/***********************************************************************
 *
 * SET processing
 *
 ***********************************************************************/

/*----------------------------------------------------------------------
 *
 * SET: Syntax checks
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Check the syntax for a particular column
 */
NETSNMP_STATIC_INLINE int
_estoqueTable_check_column( estoqueTable_rowreq_ctx *rowreq_ctx,
                         netsnmp_variable_list *var, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:estoqueTable:_estoqueTable_check_column",
                "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {
    /* (INDEX) estoqueIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/d/h */
    case COLUMN_ESTOQUEINDEX:
        rc = SNMP_ERR_NOTWRITABLE; /* can not change index of active row */
        break;

    /* name(2)/DisplayString/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/H */
    case COLUMN_NAME:
    rc = netsnmp_check_vb_type_and_max_size( var, ASN_OCTET_STR,
        sizeof( rowreq_ctx->data.name ) );
    /* check defined range(s). */
    if( (SNMPERR_SUCCESS == rc)
       && ((var->val_len < 0) || (var->val_len > 255))
     ) {
        rc = SNMP_ERR_WRONGLENGTH;
    }
    if(SNMPERR_SUCCESS != rc) {
        DEBUGMSGTL(("estoqueTable:_estoqueTable_check_column:name",
                    "varbind validation failed (eg bad type or size)\n"));
    }
    else {
        rc = name_check_value( rowreq_ctx, (char *)var->val.string, var->val_len );
        if((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc) &&
           (MFD_NOT_VALID_NOW != rc)) {
            snmp_log(LOG_ERR, "bad rc %d from name_check_value\n", rc);
            rc = SNMP_ERR_GENERR;
        }
    }
        break;

    /* amount(3)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/d/h */
    case COLUMN_AMOUNT:
    rc = netsnmp_check_vb_type_and_size( var, ASN_INTEGER,
        sizeof( rowreq_ctx->data.amount ) );
    if(SNMPERR_SUCCESS != rc) {
        DEBUGMSGTL(("estoqueTable:_estoqueTable_check_column:amount",
                    "varbind validation failed (eg bad type or size)\n"));
    }
    else {
        rc = amount_check_value( rowreq_ctx, *((long *)var->val.string) );
        if((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc) &&
           (MFD_NOT_VALID_NOW != rc)) {
            snmp_log(LOG_ERR, "bad rc %d from amount_check_value\n", rc);
            rc = SNMP_ERR_GENERR;
        }
    }
        break;

        default: /** We shouldn't get here */
            rc = SNMP_ERR_GENERR;
            snmp_log(LOG_ERR, "unknown column %d in _estoqueTable_check_column\n", column);
    }

    return rc;
} /* _estoqueTable_check_column */

int
_mfd_estoqueTable_check_objects(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    estoqueTable_rowreq_ctx *rowreq_ctx = (estoqueTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info * tri;
    int                          rc;

    DEBUGMSGTL(("internal:estoqueTable:_mfd_estoqueTable_check_objects","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    for(;requests; requests = requests->next) {

        /*
         * get column number from table request info, and check that column
         */
        tri = netsnmp_extract_table_info(requests);
        if(NULL == tri)
            continue;

        rc = _estoqueTable_check_column(rowreq_ctx, requests->requestvb, tri->colnum);
        if(rc) {
            netsnmp_request_set_error(requests, SNMP_VALIDATE_ERR(rc));
            break;
        }

    } /* for results */

    return SNMP_ERR_NOERROR;
} /* _mfd_estoqueTable_check_objects */


/*----------------------------------------------------------------------
 *
 * SET: Undo setup
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Set the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_estoqueTable_undo_setup_column( estoqueTable_rowreq_ctx *rowreq_ctx, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:estoqueTable:_estoqueTable_undo_setup_column",
                "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {

    /* name(2)/DisplayString/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/H */
    case COLUMN_NAME:
        rowreq_ctx->column_set_flags |= COLUMN_NAME_FLAG;
        rc = name_undo_setup(rowreq_ctx );
        break;

    /* amount(3)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/d/h */
    case COLUMN_AMOUNT:
        rowreq_ctx->column_set_flags |= COLUMN_AMOUNT_FLAG;
        rc = amount_undo_setup(rowreq_ctx );
        break;

     default:
         snmp_log(LOG_ERR,"unknown column %d in _estoqueTable_undo_setup_column\n", column);
         break;
    }

    return rc;
} /* _estoqueTable_undo_setup_column */


/**
 * @internal
 * undo setup
 */
int
_mfd_estoqueTable_undo_setup(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc;
    estoqueTable_rowreq_ctx *rowreq_ctx = (estoqueTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);

    DEBUGMSGTL(("internal:estoqueTable:_mfd_estoqueTable_undo_setup","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * allocate undo context
     */
    rowreq_ctx->undo = estoqueTable_allocate_data();
    if(NULL == rowreq_ctx->undo) {
        /** msg already logged */
        netsnmp_request_set_error_all(requests, SNMP_ERR_RESOURCEUNAVAILABLE);
        return SNMP_ERR_NOERROR;
    }

    /*
     * row undo setup
     */
    rowreq_ctx->column_set_flags = 0;
    rc = estoqueTable_undo_setup(rowreq_ctx);
    if (MFD_SUCCESS != rc)  {
        DEBUGMSGTL(("estoqueTable:mfd","error %d from "
                    "estoqueTable_undo_setup\n", rc));
        netsnmp_request_set_error_all(requests, SNMP_VALIDATE_ERR(rc));
    }
    else {
        /*
         * column undo setup
         */
        netsnmp_table_request_info * tri;
        for(;requests; requests = requests->next) {
            /*
             * set column data
             */
            tri = netsnmp_extract_table_info(requests);
            if(NULL == tri)
                continue;
            
            rc = _estoqueTable_undo_setup_column(rowreq_ctx, tri->colnum);
            if(MFD_SUCCESS != rc)  {
                DEBUGMSGTL(("estoqueTable:mfd","error %d from "
                            "estoqueTable_undo_setup_column\n", rc));
                netsnmp_set_request_error(agtreq_info, requests, SNMP_VALIDATE_ERR(rc));
            }
        } /* for results */
    }
    
    return SNMP_ERR_NOERROR;
} /* _mfd_estoqueTable_undo_setup */

/**
 * @internal
 * undo setup
 */
int
_mfd_estoqueTable_undo_cleanup(netsnmp_mib_handler *handler,
                             netsnmp_handler_registration *reginfo,
                             netsnmp_agent_request_info *agtreq_info,
                             netsnmp_request_info *requests)
{
    estoqueTable_rowreq_ctx *rowreq_ctx = (estoqueTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    int rc;

    DEBUGMSGTL(("internal:estoqueTable:_mfd_estoqueTable_undo_cleanup","called\n"));

    /*
     * failed row create in early stages has no rowreq_ctx
     */
    if (NULL == rowreq_ctx)
        return MFD_SUCCESS;

    /*
     * call user cleanup
     */
    rc = estoqueTable_undo_cleanup(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("estoqueTable:mfd","error %d from "
                    "estoqueTable_undo_cleanup\n", rc));
    }

    /*
     * release undo context, if needed
     */
    if(rowreq_ctx->undo) {
         estoqueTable_release_data(rowreq_ctx->undo);
         rowreq_ctx->undo = NULL;
    }


    return SNMP_ERR_NOERROR;
} /* _mfd_estoqueTable_undo_cleanup */

/*----------------------------------------------------------------------
 *
 * SET: Set values
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Set the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_estoqueTable_set_column( estoqueTable_rowreq_ctx *rowreq_ctx,
                       netsnmp_variable_list *var, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:estoqueTable:_estoqueTable_set_column",
                "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {

    /* name(2)/DisplayString/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/H */
    case COLUMN_NAME:
        rowreq_ctx->column_set_flags |= COLUMN_NAME_FLAG;
        rc = name_set(rowreq_ctx, (char *)var->val.string, var->val_len );
        break;

    /* amount(3)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/d/h */
    case COLUMN_AMOUNT:
        rowreq_ctx->column_set_flags |= COLUMN_AMOUNT_FLAG;
        rc = amount_set(rowreq_ctx, *((long *)var->val.string) );
        break;

     default:
         snmp_log(LOG_ERR,"unknown column %d in _estoqueTable_set_column\n", column);
         rc = SNMP_ERR_GENERR;
         break;
    }
    
    return rc;
} /* _estoqueTable_set_column */

int
_mfd_estoqueTable_set_values(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    estoqueTable_rowreq_ctx *rowreq_ctx = (estoqueTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info * tri;
    int                          rc = SNMP_ERR_NOERROR;

    DEBUGMSGTL(("internal:estoqueTable:_mfd_estoqueTable_set_values","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    rowreq_ctx->column_set_flags = 0;
    for(;requests; requests = requests->next) {
        /*
         * set column data
         */
        tri = netsnmp_extract_table_info(requests);
        if(NULL == tri)
            continue;
        
        rc = _estoqueTable_set_column(rowreq_ctx,
                                    requests->requestvb, tri->colnum);
        if(MFD_SUCCESS != rc)  {
            DEBUGMSGTL(("estoqueTable:mfd","error %d from "
                        "estoqueTable_set_column\n", rc));
            netsnmp_set_request_error(agtreq_info, requests, SNMP_VALIDATE_ERR(rc));
        }
    } /* for results */

    return SNMP_ERR_NOERROR;
} /* _mfd_estoqueTable_set_values */

/*----------------------------------------------------------------------
 *
 * SET: commit
 *
 *---------------------------------------------------------------------*/
/**
 * @internal
 * commit the values
 */
int
_mfd_estoqueTable_commit(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc;
    estoqueTable_rowreq_ctx *rowreq_ctx = (estoqueTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);

    DEBUGMSGTL(("internal:estoqueTable:_mfd_estoqueTable_commit","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    rc = estoqueTable_commit(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        DEBUGMSGTL(("estoqueTable:mfd","error %d from "
                    "estoqueTable_commit\n", rc));
        netsnmp_request_set_error_all(requests, SNMP_VALIDATE_ERR(rc));
    }

    if (rowreq_ctx->rowreq_flags & MFD_ROW_DIRTY) {
        /*
         * if we successfully commited this row, set the dirty flag. Use the
         * current value + 1 (i.e. dirty = # rows changed).
         * this is checked in post_request...
         */
        estoqueTable_dirty_set( estoqueTable_dirty_get() + 1 ); /* set table dirty flag */
    }

    return SNMP_ERR_NOERROR;
}

int
_mfd_estoqueTable_undo_commit(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc;
    estoqueTable_rowreq_ctx *rowreq_ctx = (estoqueTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);

    DEBUGMSGTL(("internal:estoqueTable:_mfd_estoqueTable_undo_commit","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    if (rowreq_ctx->rowreq_flags & MFD_ROW_DIRTY) {
        u_int  d = estoqueTable_dirty_get();

        netsnmp_assert(d != 0);
        if(d)
            estoqueTable_dirty_set( d - 1 );
    }

    rc = estoqueTable_undo_commit(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("estoqueTable:mfd","error %d from "
                    "estoqueTable_undo_commit\n", rc));
    }

    if (rowreq_ctx->rowreq_flags & MFD_ROW_DIRTY) {
        snmp_log(LOG_WARNING, "estoqueTable row dirty flag still set after undo_commit\n");
        rowreq_ctx->rowreq_flags &= ~MFD_ROW_DIRTY;
    }

    return SNMP_ERR_NOERROR;
} /* _mfd_estoqueTable_commit */

/*----------------------------------------------------------------------
 *
 * SET: Undo
 *
 *---------------------------------------------------------------------*/
/**
 * @internal
 * undo the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_estoqueTable_undo_column( estoqueTable_rowreq_ctx *rowreq_ctx,
                       netsnmp_variable_list *var, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:estoqueTable:_estoqueTable_undo_column",
                "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {

    /* name(2)/DisplayString/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/H */
    case COLUMN_NAME:
        rc = name_undo(rowreq_ctx);
        break;

    /* amount(3)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/d/h */
    case COLUMN_AMOUNT:
        rc = amount_undo(rowreq_ctx);
        break;

     default:
         snmp_log(LOG_ERR,"unknown column %d in _estoqueTable_undo_column\n", column);
         break;
    }

    return rc;
} /* _estoqueTable_undo_column */

int
_mfd_estoqueTable_undo_values(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc;
    estoqueTable_rowreq_ctx *rowreq_ctx = (estoqueTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info * tri;

    DEBUGMSGTL(("internal:estoqueTable:_mfd_estoqueTable_undo_values","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    rc = estoqueTable_undo(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("estoqueTable:mfd","error %d from "
                    "estoqueTable_undo\n", rc));
    }
    
    for(;requests; requests = requests->next) {
        /*
         * set column data
         */
        tri = netsnmp_extract_table_info(requests);
        if(NULL == tri)
            continue;
        
        rc = _estoqueTable_undo_column(rowreq_ctx, requests->requestvb,
                                     tri->colnum);
        if (MFD_SUCCESS != rc) {
            /*
             * nothing we can do about it but log it
             */
            DEBUGMSGTL(("estoqueTable:mfd","error %d from "
                        "estoqueTable_undo_column\n", rc));
        }
    } /* for results */

    return SNMP_ERR_NOERROR;
} /* _mfd_estoqueTable_undo_values */

/*----------------------------------------------------------------------
 *
 * SET: irreversible commit
 *
 *---------------------------------------------------------------------*/
/**
 * @internal
 * commit irreversible actions
 */
int
_mfd_estoqueTable_irreversible_commit(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    estoqueTable_rowreq_ctx *rowreq_ctx = (estoqueTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    
    DEBUGMSGTL(("internal:estoqueTable:_mfd_estoqueTable_irreversible:commit","called\n"));
   
    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * check for and handle row creation/deletion
     * and update column exist flags...
     */
    if (rowreq_ctx->rowreq_flags & MFD_ROW_DELETED) {
        if (! (rowreq_ctx->rowreq_flags & MFD_ROW_CREATED))
            CONTAINER_REMOVE(estoqueTable_if_ctx.container, rowreq_ctx);
    }
    else {
        if (rowreq_ctx->column_set_flags) {
           rowreq_ctx->column_set_flags = 0;
        }
    }

    return SNMP_ERR_NOERROR;
} /* _mfd_estoqueTable_irreversible_commit */

/***********************************************************************
 *
 * DATA ACCESS
 *
 ***********************************************************************/
static void _container_free(netsnmp_container *container);

/**
 * @internal
 */
static int
_cache_load(netsnmp_cache *cache, void *vmagic)
{
    DEBUGMSGTL(("internal:estoqueTable:_cache_load","called\n"));

    if((NULL == cache) || (NULL == cache->magic)) {
        snmp_log(LOG_ERR, "invalid cache for estoqueTable_cache_load\n");
        return -1;
    }

    /** should only be called for an invalid or expired cache */
    netsnmp_assert((0 == cache->valid) || (1 == cache->expired));
    
    /*
     * call user code
     */
    return estoqueTable_container_load((netsnmp_container*)cache->magic);
} /* _cache_load */

/**
 * @internal
 */
static void
_cache_free(netsnmp_cache *cache, void *magic)
{
    netsnmp_container *container;

    DEBUGMSGTL(("internal:estoqueTable:_cache_free","called\n"));

    if((NULL == cache) || (NULL == cache->magic)) {
        snmp_log(LOG_ERR, "invalid cache in estoqueTable_cache_free\n");
        return;
    }

    container = (netsnmp_container*)cache->magic;

    _container_free(container);
} /* _cache_free */

/**
 * @internal
 */
static void
_container_item_free(estoqueTable_rowreq_ctx *rowreq_ctx, void *context)
{
    DEBUGMSGTL(("internal:estoqueTable:_container_item_free","called\n"));

    if(NULL == rowreq_ctx)
        return;

    estoqueTable_release_rowreq_ctx(rowreq_ctx);
} /* _container_item_free */

/**
 * @internal
 */
static void
_container_free(netsnmp_container *container)
{
    DEBUGMSGTL(("internal:estoqueTable:_container_free","called\n"));

    if (NULL == container) {
        snmp_log(LOG_ERR, "invalid container in estoqueTable_container_free\n");
        return;
    }

    /*
     * call user code
     */
    estoqueTable_container_free(container);
    
    /*
     * free all items. inefficient, but easy.
     */
    CONTAINER_CLEAR(container,
                    (netsnmp_container_obj_func *)_container_item_free,
                    NULL);
} /* _container_free */

/**
 * @internal
 * initialize the container with functions or wrappers
 */
void
_estoqueTable_container_init(estoqueTable_interface_ctx *if_ctx)
{
    DEBUGMSGTL(("internal:estoqueTable:_estoqueTable_container_init","called\n"));

    /*
     * cache init
     */
    if_ctx->cache = netsnmp_cache_create(30, /* timeout in seconds */
                                         _cache_load, _cache_free,
                                         estoqueTable_oid,
                                         estoqueTable_oid_size);

    if(NULL == if_ctx->cache) {
        snmp_log(LOG_ERR, "error creating cache for estoqueTable\n");
        return;
    }

    if_ctx->cache->flags = NETSNMP_CACHE_DONT_INVALIDATE_ON_SET;

    estoqueTable_container_init(&if_ctx->container, if_ctx->cache);
    if(NULL == if_ctx->container)
        if_ctx->container = netsnmp_container_find("estoqueTable:table_container");
    if(NULL == if_ctx->container) {
        snmp_log(LOG_ERR,"error creating container in "
                 "estoqueTable_container_init\n");
        return;
    }

    if (NULL != if_ctx->cache)
        if_ctx->cache->magic = (void*)if_ctx->container;
} /* _estoqueTable_container_init */

/**
 * @internal
 * shutdown the container with functions or wrappers
 */
void
_estoqueTable_container_shutdown(estoqueTable_interface_ctx *if_ctx)
{
    DEBUGMSGTL(("internal:estoqueTable:_estoqueTable_container_shutdown","called\n"));

    estoqueTable_container_shutdown(if_ctx->container);

    _container_free(if_ctx->container);

} /* _estoqueTable_container_shutdown */


estoqueTable_rowreq_ctx *
estoqueTable_row_find_by_mib_index(estoqueTable_mib_index *mib_idx)
{
    estoqueTable_rowreq_ctx   *rowreq_ctx;
    oid                      oid_tmp[MAX_OID_LEN];
    netsnmp_index            oid_idx;
    int                      rc;

    /*
     * set up storage for OID
     */
    oid_idx.oids = oid_tmp;
    oid_idx.len = sizeof(oid_tmp)/sizeof(oid);

    /*
     * convert
     */
    rc = estoqueTable_index_to_oid(&oid_idx, mib_idx);
    if (MFD_SUCCESS != rc)
        return NULL;

    rowreq_ctx = (estoqueTable_rowreq_ctx*)CONTAINER_FIND(estoqueTable_if_ctx.container, &oid_idx);

    return rowreq_ctx;
}

