/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
#ifndef ESTOQUETABLE_DATA_ACCESS_H
#define ESTOQUETABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table estoqueTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RestCtrl-MIB::estoqueTable is subid 9 of restCtrl.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.12619.9, length: 8
*/


    int estoqueTable_init_data(estoqueTable_registration * estoqueTable_reg);


    /*
     * TODO:180:o: Review estoqueTable cache timeout.
     * The number of seconds before the cache times out
     */
#define ESTOQUETABLE_CACHE_TIMEOUT   10

void estoqueTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
void estoqueTable_container_shutdown(netsnmp_container *container_ptr);

int estoqueTable_container_load(netsnmp_container *container);
void estoqueTable_container_free(netsnmp_container *container);

int estoqueTable_cache_load(netsnmp_container *container);
void estoqueTable_cache_free(netsnmp_container *container);

    int estoqueTable_row_prep( estoqueTable_rowreq_ctx *rowreq_ctx);



#ifdef __cplusplus
}
#endif

#endif /* ESTOQUETABLE_DATA_ACCESS_H */
