/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 *
 * $Id:$
 */
#ifndef ESTOQUETABLE_OIDS_H
#define ESTOQUETABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table estoqueTable */
#define ESTOQUETABLE_OID              1,3,6,1,4,1,12619,9


#define COLUMN_ESTOQUEINDEX         1
#define COLUMN_ESTOQUEINDEX_FLAG    (0x1 << 0)
    
#define COLUMN_NAME         2
#define COLUMN_NAME_FLAG    (0x1 << 1)
    
#define COLUMN_AMOUNT         3
#define COLUMN_AMOUNT_FLAG    (0x1 << 2)
    

#define ESTOQUETABLE_MIN_COL   COLUMN_ESTOQUEINDEX
#define ESTOQUETABLE_MAX_COL   COLUMN_AMOUNT
    

    /*
     * TODO:405:r: Review ESTOQUETABLE_SETTABLE_COLS macro.
     * OR together all the writable cols.
     */
#define ESTOQUETABLE_SETTABLE_COLS (COLUMN_ESTOQUEINDEX_FLAG | COLUMN_NAME_FLAG | COLUMN_AMOUNT_FLAG)

#ifdef __cplusplus
}
#endif

#endif /* ESTOQUETABLE_OIDS_H */
