/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "estoqueTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement estoqueTable get routines.
 * TODO:240:M: Implement estoqueTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table estoqueTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RestCtrl-MIB::estoqueTable is subid 9 of restCtrl.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.12619.9, length: 8
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement estoqueTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param estoqueIndex_val
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
estoqueTable_indexes_set_tbl_idx(estoqueTable_mib_index *tbl_idx, long estoqueIndex_val)
{
    DEBUGMSGTL(("verbose:estoqueTable:estoqueTable_indexes_set_tbl_idx","called\n"));

    /* estoqueIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/d/h */
    tbl_idx->estoqueIndex = estoqueIndex_val;
    

    return MFD_SUCCESS;
} /* estoqueTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
estoqueTable_indexes_set(estoqueTable_rowreq_ctx *rowreq_ctx, long estoqueIndex_val)
{
    DEBUGMSGTL(("verbose:estoqueTable:estoqueTable_indexes_set","called\n"));

    if(MFD_SUCCESS != estoqueTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , estoqueIndex_val
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != estoqueTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* estoqueTable_indexes_set */


/*---------------------------------------------------------------------
 * RestCtrl-MIB::estoqueEntry.name
 * name is subid 2 of estoqueEntry.
 * Its status is Mandatory, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.12619.9.1.2
 * Description:
Descricao do item
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   1
 *   hint: 255a
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is DisplayString (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 255)
 */
/**
 * Extract the current value of the name data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param name_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param name_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by name.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*name_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update name_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
name_get( estoqueTable_rowreq_ctx *rowreq_ctx, char **name_val_ptr_ptr, size_t *name_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != name_val_ptr_ptr) && (NULL != *name_val_ptr_ptr));
   netsnmp_assert( NULL != name_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:estoqueTable:name_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the name data.
 * copy (* name_val_ptr_ptr ) data and (* name_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for name data
     */
    if ((NULL == (* name_val_ptr_ptr )) ||
        ((* name_val_ptr_len_ptr ) <
         (rowreq_ctx->data.name_len* sizeof(rowreq_ctx->data.name[0])))) {
        /*
         * allocate space for name data
         */
        (* name_val_ptr_ptr ) = malloc(rowreq_ctx->data.name_len* sizeof(rowreq_ctx->data.name[0]));
        if(NULL == (* name_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory (rowreq_ctx->data.name)\n");
            return MFD_ERROR;
        }
    }
    (* name_val_ptr_len_ptr ) = rowreq_ctx->data.name_len* sizeof(rowreq_ctx->data.name[0]);
    memcpy( (* name_val_ptr_ptr ), rowreq_ctx->data.name, rowreq_ctx->data.name_len* sizeof(rowreq_ctx->data.name[0]) );

    return MFD_SUCCESS;
} /* name_get */

/*---------------------------------------------------------------------
 * RestCtrl-MIB::estoqueEntry.amount
 * amount is subid 3 of estoqueEntry.
 * Its status is Mandatory, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.12619.9.1.3
 * Description:
Quantidade ainda disponivel, em kg
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the amount data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param amount_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
amount_get( estoqueTable_rowreq_ctx *rowreq_ctx, long * amount_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != amount_val_ptr );


    DEBUGMSGTL(("verbose:estoqueTable:amount_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the amount data.
 * copy (* amount_val_ptr ) from rowreq_ctx->data
 */
    (* amount_val_ptr ) = rowreq_ctx->data.amount;

    return MFD_SUCCESS;
} /* amount_get */



/** @} */
