/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef ESTOQUETABLE_INTERFACE_H
#define ESTOQUETABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "estoqueTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _estoqueTable_initialize_interface(estoqueTable_registration * user_ctx,
                                    u_long flags);
void _estoqueTable_shutdown_interface(estoqueTable_registration * user_ctx);

estoqueTable_registration *
estoqueTable_registration_get( void );

estoqueTable_registration *
estoqueTable_registration_set( estoqueTable_registration * newreg );

netsnmp_container *estoqueTable_container_get( void );
int estoqueTable_container_size( void );

u_int estoqueTable_dirty_get( void );
void estoqueTable_dirty_set( u_int status );

    estoqueTable_rowreq_ctx * estoqueTable_allocate_rowreq_ctx(void *);
void estoqueTable_release_rowreq_ctx(estoqueTable_rowreq_ctx *rowreq_ctx);

int estoqueTable_index_to_oid(netsnmp_index *oid_idx,
                            estoqueTable_mib_index *mib_idx);
int estoqueTable_index_from_oid(netsnmp_index *oid_idx,
                              estoqueTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void estoqueTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* ESTOQUETABLE_INTERFACE_H */
/** @} */
