/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "estoqueTrap.h"
#include "lib_restaurante.h"

extern const oid snmptrap_oid[];
extern const size_t snmptrap_oid_len;

int
send_estoqueItemChange_trap( long estoqueIndex, char* name, unsigned long amount )
{
    netsnmp_variable_list  *var_list = NULL;
    const oid estoqueItemChange_oid[] = { 1,3,6,1,4,1,12619,11,1 };
    const oid estoqueIndex_oid[] = { 1,3,6,1,4,1,12619,9,1,1 };
    const oid name_oid[] =         { 1,3,6,1,4,1,12619,9,1,2 };
    const oid amount_oid[] =       { 1,3,6,1,4,1,12619,9,1,3 };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list, snmptrap_oid, snmptrap_oid_len, ASN_OBJECT_ID, estoqueItemChange_oid, sizeof(estoqueItemChange_oid));
    
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
        estoqueIndex_oid, OID_LENGTH(estoqueIndex_oid),
        ASN_INTEGER,
        /* Set an appropriate value for estoqueIndex */
        &estoqueIndex, sizeof(estoqueIndex));
    snmp_varlist_add_variable(&var_list,
        name_oid, OID_LENGTH(name_oid),
        ASN_OCTET_STR,
        /* Set an appropriate value for name */
        name, strlen(name));
    snmp_varlist_add_variable(&var_list,
        amount_oid, OID_LENGTH(amount_oid),
        ASN_INTEGER,
        /* Set an appropriate value for amount */
        &amount, sizeof(amount));

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
