/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
#ifndef ESTOQUETABLE_H
#define ESTOQUETABLE_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup misc misc: Miscellaneous routines
 *
 * @{
 */
#include <net-snmp/library/asn1.h>

/* other required module components */
    /* *INDENT-OFF*  */
config_add_mib(RestCtrl-MIB)
config_require(RestCtrl-MIB/estoqueTable/estoqueTable_interface)
config_require(RestCtrl-MIB/estoqueTable/estoqueTable_data_access)
config_require(RestCtrl-MIB/estoqueTable/estoqueTable_data_get)
config_require(RestCtrl-MIB/estoqueTable/estoqueTable_data_set)
    /* *INDENT-ON*  */

/* OID and column number definitions for estoqueTable */
#include "estoqueTable_oids.h"

/* enum definions */
#include "estoqueTable_enums.h"

/* *********************************************************************
 * function declarations
 */
void init_estoqueTable(void);
void shutdown_estoqueTable(void);

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table estoqueTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RestCtrl-MIB::estoqueTable is subid 9 of restCtrl.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.12619.9, length: 8
*/
/* *********************************************************************
 * When you register your mib, you get to provide a generic
 * pointer that will be passed back to you for most of the
 * functions calls.
 *
 * TODO:100:r: Review all context structures
 */
    /*
     * TODO:101:o: |-> Review estoqueTable registration context.
     */
typedef netsnmp_data_list estoqueTable_registration;

/**********************************************************************/
/*
 * TODO:110:r: |-> Review estoqueTable data context structure.
 * This structure is used to represent the data for estoqueTable.
 */
/*
 * This structure contains storage for all the columns defined in the
 * estoqueTable.
 */
typedef struct estoqueTable_data_s {
    
        /*
         * name(2)/DisplayString/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/H
         */
   char   name[255];
size_t      name_len; /* # of char elements, not bytes */
    
        /*
         * amount(3)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/d/h
         */
   long   amount;
    
} estoqueTable_data;


/* *********************************************************************
 * TODO:115:o: |-> Review estoqueTable undo context.
 * We're just going to use the same data structure for our
 * undo_context. If you want to do something more efficent,
 * define your typedef here.
 */
typedef estoqueTable_data estoqueTable_undo_data;

/*
 * TODO:120:r: |-> Review estoqueTable mib index.
 * This structure is used to represent the index for estoqueTable.
 */
typedef struct estoqueTable_mib_index_s {

        /*
         * estoqueIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/d/h
         */
   long   estoqueIndex;


} estoqueTable_mib_index;

    /*
     * TODO:121:r: |   |-> Review estoqueTable max index length.
     * If you KNOW that your indexes will never exceed a certain
     * length, update this macro to that length.
*/
#define MAX_estoqueTable_IDX_LEN     1


/* *********************************************************************
 * TODO:130:o: |-> Review estoqueTable Row request (rowreq) context.
 * When your functions are called, you will be passed a
 * estoqueTable_rowreq_ctx pointer.
 */
typedef struct estoqueTable_rowreq_ctx_s {

    /** this must be first for container compare to work */
    netsnmp_index        oid_idx;
    oid                  oid_tmp[MAX_estoqueTable_IDX_LEN];
    
    estoqueTable_mib_index        tbl_idx;
    
    estoqueTable_data              data;
    estoqueTable_undo_data       * undo;
    unsigned int                column_set_flags; /* flags for set columns */


    /*
     * flags per row. Currently, the first (lower) 8 bits are reserved
     * for the user. See mfd.h for other flags.
     */
    u_int                       rowreq_flags;

    /*
     * TODO:131:o: |   |-> Add useful data to estoqueTable rowreq context.
     */
    
    /*
     * storage for future expansion
     */
    netsnmp_data_list             *estoqueTable_data_list;

} estoqueTable_rowreq_ctx;

typedef struct estoqueTable_ref_rowreq_ctx_s {
    estoqueTable_rowreq_ctx *rowreq_ctx;
} estoqueTable_ref_rowreq_ctx;

/* *********************************************************************
 * function prototypes
 */
    int estoqueTable_pre_request(estoqueTable_registration * user_context);
    int estoqueTable_post_request(estoqueTable_registration * user_context,
        int rc);

    int estoqueTable_rowreq_ctx_init(estoqueTable_rowreq_ctx *rowreq_ctx,
                                   void *user_init_ctx);
    void estoqueTable_rowreq_ctx_cleanup(estoqueTable_rowreq_ctx *rowreq_ctx);

    int estoqueTable_commit(estoqueTable_rowreq_ctx * rowreq_ctx);

    estoqueTable_rowreq_ctx *
                  estoqueTable_row_find_by_mib_index(estoqueTable_mib_index *mib_idx);

extern const oid estoqueTable_oid[];
extern const int estoqueTable_oid_size;


#include "estoqueTable_interface.h"
#include "estoqueTable_data_access.h"
#include "estoqueTable_data_get.h"
#include "estoqueTable_data_set.h"

/*
 * DUMMY markers, ignore
 *
 * TODO:099:x: *************************************************************
 * TODO:199:x: *************************************************************
 * TODO:299:x: *************************************************************
 * TODO:399:x: *************************************************************
 * TODO:499:x: *************************************************************
 */

#ifdef __cplusplus
}
#endif

#endif /* ESTOQUETABLE_H */
/** @} */
