/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
#ifndef ESTOQUETABLE_DATA_SET_H
#define ESTOQUETABLE_DATA_SET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * SET function declarations
 */

/* *********************************************************************
 * SET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table estoqueTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RestCtrl-MIB::estoqueTable is subid 9 of restCtrl.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.12619.9, length: 8
*/


int estoqueTable_undo_setup( estoqueTable_rowreq_ctx *rowreq_ctx);
int estoqueTable_undo_cleanup( estoqueTable_rowreq_ctx *rowreq_ctx);
int estoqueTable_undo( estoqueTable_rowreq_ctx *rowreq_ctx);
int estoqueTable_commit( estoqueTable_rowreq_ctx *rowreq_ctx);
int estoqueTable_undo_commit( estoqueTable_rowreq_ctx *rowreq_ctx);


int name_check_value( estoqueTable_rowreq_ctx *rowreq_ctx, char *name_val_ptr,  size_t name_val_ptr_len);
int name_undo_setup( estoqueTable_rowreq_ctx *rowreq_ctx );
int name_set( estoqueTable_rowreq_ctx *rowreq_ctx, char *name_val_ptr,  size_t name_val_ptr_len );
int name_undo( estoqueTable_rowreq_ctx *rowreq_ctx );

int amount_check_value( estoqueTable_rowreq_ctx *rowreq_ctx, long amount_val);
int amount_undo_setup( estoqueTable_rowreq_ctx *rowreq_ctx );
int amount_set( estoqueTable_rowreq_ctx *rowreq_ctx, long amount_val );
int amount_undo( estoqueTable_rowreq_ctx *rowreq_ctx );


int estoqueTable_check_dependencies(estoqueTable_rowreq_ctx *ctx);


#ifdef __cplusplus
}
#endif

#endif /* ESTOQUETABLE_DATA_SET_H */
