/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "lotAtual.h"

/** Initializes the lotAtual module */
void
init_lotAtual(void)
{
    const oid lotAtual_oid[] = { 1,3,6,1,4,1,12619,2 };

  DEBUGMSGTL(("lotAtual", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("lotAtual", handle_lotAtual,
                               lotAtual_oid, OID_LENGTH(lotAtual_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_lotAtual(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    // Modifications made by Roberto   
    FILE *output;
    char app_path[120] = APP_PYTHON_PATH;
    char buffer[20];
    unsigned long cap;
    // End of modifications by Roberto	

    switch(reqinfo->mode) {

        case MODE_GET:

			// Modifications made by Roberto
			strcat(app_path, "-c");
			syslog(LOG_INFO, "app_path: %s", app_path);
			output = popen (app_path, "r"); // Call the restaurante app, and parse the ouput
			if (!output)
			{
				syslog (LOG_INFO,"incorrect parameters or too many files.\n");
				return EXIT_FAILURE;
			}
			fgets(buffer, 10, output);
			cap = strtoul(buffer, NULL, 10);
			// End of modifications by Roberto	

            snmp_set_var_typed_value(requests->requestvb, ASN_COUNTER,&cap, sizeof(cap));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_lotAtual\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
