/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef LOTATUAL_H
#define LOTATUAL_H

/* function declarations */
void init_lotAtual(void);
Netsnmp_Node_Handler handle_lotAtual;

#endif /* LOTATUAL_H */
