/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
/** \page MFD helper for menuTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "menuTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "menuTable_interface.h"

const oid menuTable_oid[] = { MENUTABLE_OID };
const int menuTable_oid_size = OID_LENGTH(menuTable_oid);

    menuTable_registration  menuTable_user_context;

void initialize_table_menuTable(void);
void shutdown_table_menuTable(void);


/**
 * Initializes the menuTable module
 */
void
init_menuTable(void)
{
    DEBUGMSGTL(("verbose:menuTable:init_menuTable","called\n"));

    /*
     * TODO:300:o: Perform menuTable one-time module initialization.
     */
     
    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("menuTable"))
        initialize_table_menuTable();

} /* init_menuTable */

/**
 * Shut-down the menuTable module (agent is exiting)
 */
void
shutdown_menuTable(void)
{
    if (should_init("menuTable"))
        shutdown_table_menuTable();

}

/**
 * Initialize the table menuTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_menuTable(void)
{
    menuTable_registration * user_context;
    u_long flags;

    DEBUGMSGTL(("verbose:menuTable:initialize_table_menuTable","called\n"));

    /*
     * TODO:301:o: Perform menuTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize menuTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context = netsnmp_create_data_list("menuTable", NULL, NULL);
    
    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;
    
    /*
     * call interface initialization code
     */
    _menuTable_initialize_interface(user_context, flags);
} /* initialize_table_menuTable */

/**
 * Shutdown the table menuTable 
 */
void
shutdown_table_menuTable(void)
{
    /*
     * call interface shutdown code
     */
    _menuTable_shutdown_interface(&menuTable_user_context);
}

/**
 * extra context initialization (eg default values)
 *
 * @param rowreq_ctx    : row request context
 * @param user_init_ctx : void pointer for user (parameter to rowreq_ctx_allocate)
 *
 * @retval MFD_SUCCESS  : no errors
 * @retval MFD_ERROR    : error (context allocate will fail)
 */
int
menuTable_rowreq_ctx_init(menuTable_rowreq_ctx *rowreq_ctx,
                           void *user_init_ctx)
{
    DEBUGMSGTL(("verbose:menuTable:menuTable_rowreq_ctx_init","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:210:o: |-> Perform extra menuTable rowreq initialization. (eg DEFVALS)
     */

    return MFD_SUCCESS;
} /* menuTable_rowreq_ctx_init */

/**
 * extra context cleanup
 *
 */
void menuTable_rowreq_ctx_cleanup(menuTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:menuTable:menuTable_rowreq_ctx_cleanup","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:211:o: |-> Perform extra menuTable rowreq cleanup.
     */
} /* menuTable_rowreq_ctx_cleanup */

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
menuTable_pre_request(menuTable_registration * user_context)
{
    DEBUGMSGTL(("verbose:menuTable:menuTable_pre_request","called\n"));

    /*
     * TODO:510:o: Perform menuTable pre-request actions.
     */

    return MFD_SUCCESS;
} /* menuTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
menuTable_post_request(menuTable_registration * user_context, int rc)
{
    DEBUGMSGTL(("verbose:menuTable:menuTable_post_request","called\n"));

    /*
     * TODO:511:o: Perform menuTable post-request actions.
     */

    return MFD_SUCCESS;
} /* menuTable_post_request */


/** @{ */
