/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
#ifndef MENUTABLE_H
#define MENUTABLE_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup misc misc: Miscellaneous routines
 *
 * @{
 */
#include <net-snmp/library/asn1.h>

/* other required module components */
    /* *INDENT-OFF*  */
config_add_mib(RestCtrl-MIB)
config_require(RestCtrl-MIB/menuTable/menuTable_interface)
config_require(RestCtrl-MIB/menuTable/menuTable_data_access)
config_require(RestCtrl-MIB/menuTable/menuTable_data_get)
config_require(RestCtrl-MIB/menuTable/menuTable_data_set)
    /* *INDENT-ON*  */

/* OID and column number definitions for menuTable */
#include "menuTable_oids.h"

/* enum definions */
#include "menuTable_enums.h"

/* *********************************************************************
 * function declarations
 */
void init_menuTable(void);
void shutdown_menuTable(void);

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table menuTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RestCtrl-MIB::menuTable is subid 5 of restCtrl.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.12619.5, length: 8
*/
/* *********************************************************************
 * When you register your mib, you get to provide a generic
 * pointer that will be passed back to you for most of the
 * functions calls.
 *
 * TODO:100:r: Review all context structures
 */
    /*
     * TODO:101:o: |-> Review menuTable registration context.
     */
typedef netsnmp_data_list menuTable_registration;

/**********************************************************************/
/*
 * TODO:110:r: |-> Review menuTable data context structure.
 * This structure is used to represent the data for menuTable.
 */
/*
 * This structure contains storage for all the columns defined in the
 * menuTable.
 */
typedef struct menuTable_data_s {
    
        /*
         * description(2)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
   char   description[255];
size_t      description_len; /* # of char elements, not bytes */
    
} menuTable_data;


/*
 * TODO:120:r: |-> Review menuTable mib index.
 * This structure is used to represent the index for menuTable.
 */
typedef struct menuTable_mib_index_s {

        /*
         * menuIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/R/d/h
         */
   long   menuIndex;


} menuTable_mib_index;

    /*
     * TODO:121:r: |   |-> Review menuTable max index length.
     * If you KNOW that your indexes will never exceed a certain
     * length, update this macro to that length.
*/
#define MAX_menuTable_IDX_LEN     1


/* *********************************************************************
 * TODO:130:o: |-> Review menuTable Row request (rowreq) context.
 * When your functions are called, you will be passed a
 * menuTable_rowreq_ctx pointer.
 */
typedef struct menuTable_rowreq_ctx_s {

    /** this must be first for container compare to work */
    netsnmp_index        oid_idx;
    oid                  oid_tmp[MAX_menuTable_IDX_LEN];
    
    menuTable_mib_index        tbl_idx;
    
    menuTable_data              data;

    /*
     * flags per row. Currently, the first (lower) 8 bits are reserved
     * for the user. See mfd.h for other flags.
     */
    u_int                       rowreq_flags;

    /*
     * TODO:131:o: |   |-> Add useful data to menuTable rowreq context.
     */
    
    /*
     * storage for future expansion
     */
    netsnmp_data_list             *menuTable_data_list;

} menuTable_rowreq_ctx;

typedef struct menuTable_ref_rowreq_ctx_s {
    menuTable_rowreq_ctx *rowreq_ctx;
} menuTable_ref_rowreq_ctx;

/* *********************************************************************
 * function prototypes
 */
    int menuTable_pre_request(menuTable_registration * user_context);
    int menuTable_post_request(menuTable_registration * user_context,
        int rc);

    int menuTable_rowreq_ctx_init(menuTable_rowreq_ctx *rowreq_ctx,
                                   void *user_init_ctx);
    void menuTable_rowreq_ctx_cleanup(menuTable_rowreq_ctx *rowreq_ctx);


    menuTable_rowreq_ctx *
                  menuTable_row_find_by_mib_index(menuTable_mib_index *mib_idx);

extern const oid menuTable_oid[];
extern const int menuTable_oid_size;


#include "menuTable_interface.h"
#include "menuTable_data_access.h"
#include "menuTable_data_get.h"
#include "menuTable_data_set.h"

/*
 * DUMMY markers, ignore
 *
 * TODO:099:x: *************************************************************
 * TODO:199:x: *************************************************************
 * TODO:299:x: *************************************************************
 * TODO:399:x: *************************************************************
 * TODO:499:x: *************************************************************
 */

#ifdef __cplusplus
}
#endif

#endif /* MENUTABLE_H */
/** @} */
