/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
#ifndef MENUTABLE_DATA_ACCESS_H
#define MENUTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table menuTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RestCtrl-MIB::menuTable is subid 5 of restCtrl.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.12619.5, length: 8
*/


    int menuTable_init_data(menuTable_registration * menuTable_reg);


    /*
     * TODO:180:o: Review menuTable cache timeout.
     * The number of seconds before the cache times out
     */
#define MENUTABLE_CACHE_TIMEOUT   60

void menuTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
void menuTable_container_shutdown(netsnmp_container *container_ptr);

int menuTable_container_load(netsnmp_container *container);
void menuTable_container_free(netsnmp_container *container);

int menuTable_cache_load(netsnmp_container *container);
void menuTable_cache_free(netsnmp_container *container);

    int menuTable_row_prep( menuTable_rowreq_ctx *rowreq_ctx);



#ifdef __cplusplus
}
#endif

#endif /* MENUTABLE_DATA_ACCESS_H */
