/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "menuTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement menuTable get routines.
 * TODO:240:M: Implement menuTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table menuTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RestCtrl-MIB::menuTable is subid 5 of restCtrl.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.12619.5, length: 8
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement menuTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param menuIndex_val
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
menuTable_indexes_set_tbl_idx(menuTable_mib_index *tbl_idx, long menuIndex_val)
{
    DEBUGMSGTL(("verbose:menuTable:menuTable_indexes_set_tbl_idx","called\n"));

    /* menuIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/R/d/h */
    tbl_idx->menuIndex = menuIndex_val;
    

    return MFD_SUCCESS;
} /* menuTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
menuTable_indexes_set(menuTable_rowreq_ctx *rowreq_ctx, long menuIndex_val)
{
    DEBUGMSGTL(("verbose:menuTable:menuTable_indexes_set","called\n"));

    if(MFD_SUCCESS != menuTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , menuIndex_val
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != menuTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* menuTable_indexes_set */


/*---------------------------------------------------------------------
 * RestCtrl-MIB::menuEntry.description
 * description is subid 2 of menuEntry.
 * Its status is Mandatory, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.12619.5.1.2
 * Description:
Descricao do item
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   0
 *   hint: 255a
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is DisplayString (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 255)
 */
/**
 * Extract the current value of the description data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param description_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param description_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by description.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*description_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update description_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
description_get( menuTable_rowreq_ctx *rowreq_ctx, char **description_val_ptr_ptr, size_t *description_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != description_val_ptr_ptr) && (NULL != *description_val_ptr_ptr));
   netsnmp_assert( NULL != description_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:menuTable:description_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the description data.
 * copy (* description_val_ptr_ptr ) data and (* description_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for description data
     */
    if ((NULL == (* description_val_ptr_ptr )) ||
        ((* description_val_ptr_len_ptr ) <
         (rowreq_ctx->data.description_len* sizeof(rowreq_ctx->data.description[0])))) {
        /*
         * allocate space for description data
         */
        (* description_val_ptr_ptr ) = malloc(rowreq_ctx->data.description_len* sizeof(rowreq_ctx->data.description[0]));
        if(NULL == (* description_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory (rowreq_ctx->data.description)\n");
            return MFD_ERROR;
        }
    }
    (* description_val_ptr_len_ptr ) = rowreq_ctx->data.description_len* sizeof(rowreq_ctx->data.description[0]);
    memcpy( (* description_val_ptr_ptr ), rowreq_ctx->data.description, rowreq_ctx->data.description_len* sizeof(rowreq_ctx->data.description[0]) );

    return MFD_SUCCESS;
} /* description_get */



/** @} */
