/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef MENUTABLE_INTERFACE_H
#define MENUTABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "menuTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _menuTable_initialize_interface(menuTable_registration * user_ctx,
                                    u_long flags);
void _menuTable_shutdown_interface(menuTable_registration * user_ctx);

menuTable_registration *
menuTable_registration_get( void );

menuTable_registration *
menuTable_registration_set( menuTable_registration * newreg );

netsnmp_container *menuTable_container_get( void );
int menuTable_container_size( void );

    menuTable_rowreq_ctx * menuTable_allocate_rowreq_ctx(void *);
void menuTable_release_rowreq_ctx(menuTable_rowreq_ctx *rowreq_ctx);

int menuTable_index_to_oid(netsnmp_index *oid_idx,
                            menuTable_mib_index *mib_idx);
int menuTable_index_from_oid(netsnmp_index *oid_idx,
                              menuTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void menuTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* MENUTABLE_INTERFACE_H */
/** @} */
