/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 *
 * $Id:$
 */
#ifndef MENUTABLE_OIDS_H
#define MENUTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table menuTable */
#define MENUTABLE_OID              1,3,6,1,4,1,12619,5


#define COLUMN_MENUINDEX         1
    
#define COLUMN_DESCRIPTION         2
    

#define MENUTABLE_MIN_COL   COLUMN_MENUINDEX
#define MENUTABLE_MAX_COL   COLUMN_DESCRIPTION
    


#ifdef __cplusplus
}
#endif

#endif /* MENUTABLE_OIDS_H */
