/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
#ifndef MESASTABLE_DATA_ACCESS_H
#define MESASTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table mesasTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RestCtrl-MIB::mesasTable is subid 3 of restCtrl.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.12619.3, length: 8
*/


    int mesasTable_init_data(mesasTable_registration * mesasTable_reg);


    /*
     * TODO:180:o: Review mesasTable cache timeout.
     * The number of seconds before the cache times out
     */
#define MESASTABLE_CACHE_TIMEOUT   5

void mesasTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
void mesasTable_container_shutdown(netsnmp_container *container_ptr);

int mesasTable_container_load(netsnmp_container *container);
void mesasTable_container_free(netsnmp_container *container);

int mesasTable_cache_load(netsnmp_container *container);
void mesasTable_cache_free(netsnmp_container *container);

    int mesasTable_row_prep( mesasTable_rowreq_ctx *rowreq_ctx);



#ifdef __cplusplus
}
#endif

#endif /* MESASTABLE_DATA_ACCESS_H */
