/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "mesasTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement mesasTable get routines.
 * TODO:240:M: Implement mesasTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table mesasTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RestCtrl-MIB::mesasTable is subid 3 of restCtrl.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.12619.3, length: 8
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement mesasTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param mesasIndex_val
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
mesasTable_indexes_set_tbl_idx(mesasTable_mib_index *tbl_idx, long mesasIndex_val)
{
    DEBUGMSGTL(("verbose:mesasTable:mesasTable_indexes_set_tbl_idx","called\n"));

    /* mesasIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/R/d/h */
    tbl_idx->mesasIndex = mesasIndex_val;
    

    return MFD_SUCCESS;
} /* mesasTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
mesasTable_indexes_set(mesasTable_rowreq_ctx *rowreq_ctx, long mesasIndex_val)
{
    DEBUGMSGTL(("verbose:mesasTable:mesasTable_indexes_set","called\n"));

    if(MFD_SUCCESS != mesasTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , mesasIndex_val
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != mesasTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* mesasTable_indexes_set */


/*---------------------------------------------------------------------
 * RestCtrl-MIB::mesasEntry.capacidadeMesa
 * capacidadeMesa is subid 2 of mesasEntry.
 * Its status is Mandatory, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.12619.3.1.2
 * Description:
Numero maximo de clientes na mesa
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *
 * Ranges:  1 - 20;
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the capacidadeMesa data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param capacidadeMesa_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
capacidadeMesa_get( mesasTable_rowreq_ctx *rowreq_ctx, long * capacidadeMesa_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != capacidadeMesa_val_ptr );


    DEBUGMSGTL(("verbose:mesasTable:capacidadeMesa_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the capacidadeMesa data.
 * copy (* capacidadeMesa_val_ptr ) from rowreq_ctx->data
 */
    (* capacidadeMesa_val_ptr ) = rowreq_ctx->data.capacidadeMesa;

    return MFD_SUCCESS;
} /* capacidadeMesa_get */

/*---------------------------------------------------------------------
 * RestCtrl-MIB::mesasEntry.numClientes
 * numClientes is subid 3 of mesasEntry.
 * Its status is Mandatory, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.12619.3.1.3
 * Description:
Numero clientes atualmente na mesa
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *
 * Ranges:  1 - 20;
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the numClientes data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param numClientes_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
numClientes_get( mesasTable_rowreq_ctx *rowreq_ctx, long * numClientes_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != numClientes_val_ptr );


    DEBUGMSGTL(("verbose:mesasTable:numClientes_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the numClientes data.
 * copy (* numClientes_val_ptr ) from rowreq_ctx->data
 */
    (* numClientes_val_ptr ) = rowreq_ctx->data.numClientes;

    return MFD_SUCCESS;
} /* numClientes_get */

/*---------------------------------------------------------------------
 * RestCtrl-MIB::mesasEntry.status
 * status is subid 4 of mesasEntry.
 * Its status is Mandatory, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.12619.3.1.4
 * Description:
Status atual da mesa
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 * Enum range: 2/8. Values:  livre(0), ocupada(1), indisponivel(2)
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the status data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param status_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
status_get( mesasTable_rowreq_ctx *rowreq_ctx, u_long * status_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != status_val_ptr );


    DEBUGMSGTL(("verbose:mesasTable:status_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the status data.
 * copy (* status_val_ptr ) from rowreq_ctx->data
 */
    (* status_val_ptr ) = rowreq_ctx->data.status;

    return MFD_SUCCESS;
} /* status_get */



/** @} */
