/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef MESASTABLE_INTERFACE_H
#define MESASTABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "mesasTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _mesasTable_initialize_interface(mesasTable_registration * user_ctx,
                                    u_long flags);
void _mesasTable_shutdown_interface(mesasTable_registration * user_ctx);

mesasTable_registration *
mesasTable_registration_get( void );

mesasTable_registration *
mesasTable_registration_set( mesasTable_registration * newreg );

netsnmp_container *mesasTable_container_get( void );
int mesasTable_container_size( void );

    mesasTable_rowreq_ctx * mesasTable_allocate_rowreq_ctx(void *);
void mesasTable_release_rowreq_ctx(mesasTable_rowreq_ctx *rowreq_ctx);

int mesasTable_index_to_oid(netsnmp_index *oid_idx,
                            mesasTable_mib_index *mib_idx);
int mesasTable_index_from_oid(netsnmp_index *oid_idx,
                              mesasTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void mesasTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* MESASTABLE_INTERFACE_H */
/** @} */
