/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
/** \page MFD helper for mesasTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "mesasTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "mesasTable_interface.h"

const oid mesasTable_oid[] = { MESASTABLE_OID };
const int mesasTable_oid_size = OID_LENGTH(mesasTable_oid);

    mesasTable_registration  mesasTable_user_context;

void initialize_table_mesasTable(void);
void shutdown_table_mesasTable(void);


/**
 * Initializes the mesasTable module
 */
void
init_mesasTable(void)
{
    DEBUGMSGTL(("verbose:mesasTable:init_mesasTable","called\n"));

    /*
     * TODO:300:o: Perform mesasTable one-time module initialization.
     */
     
    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("mesasTable"))
        initialize_table_mesasTable();

} /* init_mesasTable */

/**
 * Shut-down the mesasTable module (agent is exiting)
 */
void
shutdown_mesasTable(void)
{
    if (should_init("mesasTable"))
        shutdown_table_mesasTable();

}

/**
 * Initialize the table mesasTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_mesasTable(void)
{
    mesasTable_registration * user_context;
    u_long flags;

    DEBUGMSGTL(("verbose:mesasTable:initialize_table_mesasTable","called\n"));

    /*
     * TODO:301:o: Perform mesasTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize mesasTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context = netsnmp_create_data_list("mesasTable", NULL, NULL);
    
    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;
    
    /*
     * call interface initialization code
     */
    _mesasTable_initialize_interface(user_context, flags);
} /* initialize_table_mesasTable */

/**
 * Shutdown the table mesasTable 
 */
void
shutdown_table_mesasTable(void)
{
    /*
     * call interface shutdown code
     */
    _mesasTable_shutdown_interface(&mesasTable_user_context);
}

/**
 * extra context initialization (eg default values)
 *
 * @param rowreq_ctx    : row request context
 * @param user_init_ctx : void pointer for user (parameter to rowreq_ctx_allocate)
 *
 * @retval MFD_SUCCESS  : no errors
 * @retval MFD_ERROR    : error (context allocate will fail)
 */
int
mesasTable_rowreq_ctx_init(mesasTable_rowreq_ctx *rowreq_ctx,
                           void *user_init_ctx)
{
    DEBUGMSGTL(("verbose:mesasTable:mesasTable_rowreq_ctx_init","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:210:o: |-> Perform extra mesasTable rowreq initialization. (eg DEFVALS)
     */

    return MFD_SUCCESS;
} /* mesasTable_rowreq_ctx_init */

/**
 * extra context cleanup
 *
 */
void mesasTable_rowreq_ctx_cleanup(mesasTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:mesasTable:mesasTable_rowreq_ctx_cleanup","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:211:o: |-> Perform extra mesasTable rowreq cleanup.
     */
} /* mesasTable_rowreq_ctx_cleanup */

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
mesasTable_pre_request(mesasTable_registration * user_context)
{
    DEBUGMSGTL(("verbose:mesasTable:mesasTable_pre_request","called\n"));

    /*
     * TODO:510:o: Perform mesasTable pre-request actions.
     */

    return MFD_SUCCESS;
} /* mesasTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
mesasTable_post_request(mesasTable_registration * user_context, int rc)
{
    DEBUGMSGTL(("verbose:mesasTable:mesasTable_post_request","called\n"));

    /*
     * TODO:511:o: Perform mesasTable post-request actions.
     */

    return MFD_SUCCESS;
} /* mesasTable_post_request */


/** @{ */
