/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 *
 * @file mesasTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef MESASTABLE_DATA_GET_H
#define MESASTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table mesasTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RestCtrl-MIB::mesasTable is subid 3 of restCtrl.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.12619.3, length: 8
*/
    /*
     * indexes
     */

    int capacidadeMesa_get( mesasTable_rowreq_ctx *rowreq_ctx, long * capacidadeMesa_val_ptr );
    int numClientes_get( mesasTable_rowreq_ctx *rowreq_ctx, long * numClientes_val_ptr );
    int status_get( mesasTable_rowreq_ctx *rowreq_ctx, u_long * status_val_ptr );


int mesasTable_indexes_set_tbl_idx(mesasTable_mib_index *tbl_idx, long mesasIndex_val);
int mesasTable_indexes_set(mesasTable_rowreq_ctx *rowreq_ctx, long mesasIndex_val);




#ifdef __cplusplus
}
#endif

#endif /* MESASTABLE_DATA_GET_H */
/** @} */
