/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 *
 * $Id:$
 */
#ifndef MESASTABLE_OIDS_H
#define MESASTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table mesasTable */
#define MESASTABLE_OID              1,3,6,1,4,1,12619,3


#define COLUMN_MESASINDEX         1
    
#define COLUMN_CAPACIDADEMESA         2
    
#define COLUMN_NUMCLIENTES         3
    
#define COLUMN_STATUS         4
    

#define MESASTABLE_MIN_COL   COLUMN_MESASINDEX
#define MESASTABLE_MAX_COL   COLUMN_STATUS
    


#ifdef __cplusplus
}
#endif

#endif /* MESASTABLE_OIDS_H */
