/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
#ifndef MESASTABLE_H
#define MESASTABLE_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup misc misc: Miscellaneous routines
 *
 * @{
 */
#include <net-snmp/library/asn1.h>

/* other required module components */
    /* *INDENT-OFF*  */
config_add_mib(RestCtrl-MIB)
config_require(RestCtrl-MIB/mesasTable/mesasTable_interface)
config_require(RestCtrl-MIB/mesasTable/mesasTable_data_access)
config_require(RestCtrl-MIB/mesasTable/mesasTable_data_get)
config_require(RestCtrl-MIB/mesasTable/mesasTable_data_set)
    /* *INDENT-ON*  */

/* OID and column number definitions for mesasTable */
#include "mesasTable_oids.h"

/* enum definions */
#include "mesasTable_enums.h"

/* *********************************************************************
 * function declarations
 */
void init_mesasTable(void);
void shutdown_mesasTable(void);

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table mesasTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RestCtrl-MIB::mesasTable is subid 3 of restCtrl.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.12619.3, length: 8
*/
/* *********************************************************************
 * When you register your mib, you get to provide a generic
 * pointer that will be passed back to you for most of the
 * functions calls.
 *
 * TODO:100:r: Review all context structures
 */
    /*
     * TODO:101:o: |-> Review mesasTable registration context.
     */
typedef netsnmp_data_list mesasTable_registration;

/**********************************************************************/
/*
 * TODO:110:r: |-> Review mesasTable data context structure.
 * This structure is used to represent the data for mesasTable.
 */
/*
 * This structure contains storage for all the columns defined in the
 * mesasTable.
 */
typedef struct mesasTable_data_s {
    
        /*
         * capacidadeMesa(2)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/R/d/h
         */
   long   capacidadeMesa;
    
        /*
         * numClientes(3)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/R/d/h
         */
   long   numClientes;
    
        /*
         * status(4)/INTEGER/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h
         */
   u_long   status;
    
} mesasTable_data;


/*
 * TODO:120:r: |-> Review mesasTable mib index.
 * This structure is used to represent the index for mesasTable.
 */
typedef struct mesasTable_mib_index_s {

        /*
         * mesasIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/R/d/h
         */
   long   mesasIndex;


} mesasTable_mib_index;

    /*
     * TODO:121:r: |   |-> Review mesasTable max index length.
     * If you KNOW that your indexes will never exceed a certain
     * length, update this macro to that length.
*/
#define MAX_mesasTable_IDX_LEN     1


/* *********************************************************************
 * TODO:130:o: |-> Review mesasTable Row request (rowreq) context.
 * When your functions are called, you will be passed a
 * mesasTable_rowreq_ctx pointer.
 */
typedef struct mesasTable_rowreq_ctx_s {

    /** this must be first for container compare to work */
    netsnmp_index        oid_idx;
    oid                  oid_tmp[MAX_mesasTable_IDX_LEN];
    
    mesasTable_mib_index        tbl_idx;
    
    mesasTable_data              data;

    /*
     * flags per row. Currently, the first (lower) 8 bits are reserved
     * for the user. See mfd.h for other flags.
     */
    u_int                       rowreq_flags;

    /*
     * TODO:131:o: |   |-> Add useful data to mesasTable rowreq context.
     */
    
    /*
     * storage for future expansion
     */
    netsnmp_data_list             *mesasTable_data_list;

} mesasTable_rowreq_ctx;

typedef struct mesasTable_ref_rowreq_ctx_s {
    mesasTable_rowreq_ctx *rowreq_ctx;
} mesasTable_ref_rowreq_ctx;

/* *********************************************************************
 * function prototypes
 */
    int mesasTable_pre_request(mesasTable_registration * user_context);
    int mesasTable_post_request(mesasTable_registration * user_context,
        int rc);

    int mesasTable_rowreq_ctx_init(mesasTable_rowreq_ctx *rowreq_ctx,
                                   void *user_init_ctx);
    void mesasTable_rowreq_ctx_cleanup(mesasTable_rowreq_ctx *rowreq_ctx);


    mesasTable_rowreq_ctx *
                  mesasTable_row_find_by_mib_index(mesasTable_mib_index *mib_idx);

extern const oid mesasTable_oid[];
extern const int mesasTable_oid_size;


#include "mesasTable_interface.h"
#include "mesasTable_data_access.h"
#include "mesasTable_data_get.h"
#include "mesasTable_data_set.h"

/*
 * DUMMY markers, ignore
 *
 * TODO:099:x: *************************************************************
 * TODO:199:x: *************************************************************
 * TODO:299:x: *************************************************************
 * TODO:399:x: *************************************************************
 * TODO:499:x: *************************************************************
 */

#ifdef __cplusplus
}
#endif

#endif /* MESASTABLE_H */
/** @} */
