/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef NUMFUNC_H
#define NUMFUNC_H

/* function declarations */
void init_numFunc(void);
Netsnmp_Node_Handler handle_numFunc;

#endif /* NUMFUNC_H */
