/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "numFunc.h"
#include "lib_restaurante.h"

/** Initializes the numFunc module */
void
init_numFunc(void)
{
    const oid numFunc_oid[] = { 1,3,6,1,4,1,12619,6 };

  DEBUGMSGTL(("numFunc", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("numFunc", handle_numFunc,
                               numFunc_oid, OID_LENGTH(numFunc_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_numFunc(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    unsigned long num_func = getNumFunc();
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_COUNTER, &num_func, sizeof(num_func) );
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_numFunc\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
