/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 *
 * $Id:$
 */
#ifndef ORDERSTABLE_ENUMS_H
#define ORDERSTABLE_ENUMS_H

#ifdef __cplusplus
extern "C" {
#endif

 /*
 * NOTES on enums
 * ==============
 *
 * Value Mapping
 * -------------
 * If the values for your data type don't exactly match the
 * possible values defined by the mib, you should map them
 * below. For example, a boolean flag (1/0) is usually represented
 * as a TruthValue in a MIB, which maps to the values (1/2).
 *
 */
/*************************************************************************
 *************************************************************************
 *
 * enum definitions for table ordersTable
 *
 *************************************************************************
 *************************************************************************/

/*************************************************************
 * constants for enums for the MIB node
 * status (INTEGER / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef STATUS_ENUMS
#define STATUS_ENUMS

#define STATUS_LIVRE  0 
#define STATUS_OCUPADA  1 
#define STATUS_INDISPONIVEL  2 

#endif /* STATUS_ENUMS */




#ifdef __cplusplus
}
#endif

#endif /* ORDERSTABLE_ENUMS_H */
