/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 *
 * @file ordersTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef ORDERSTABLE_DATA_GET_H
#define ORDERSTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table ordersTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RestCtrl-MIB::ordersTable is subid 4 of restCtrl.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.12619.4, length: 8
*/
    /*
     * indexes
     */

    int item_get( ordersTable_rowreq_ctx *rowreq_ctx, long * item_val_ptr );
    int table_get( ordersTable_rowreq_ctx *rowreq_ctx, long * table_val_ptr );
    int status_get( ordersTable_rowreq_ctx *rowreq_ctx, u_long * status_val_ptr );


int ordersTable_indexes_set_tbl_idx(ordersTable_mib_index *tbl_idx, long ordersIndex_val);
int ordersTable_indexes_set(ordersTable_rowreq_ctx *rowreq_ctx, long ordersIndex_val);




#ifdef __cplusplus
}
#endif

#endif /* ORDERSTABLE_DATA_GET_H */
/** @} */
