/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
#ifndef ORDERSTABLE_DATA_ACCESS_H
#define ORDERSTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table ordersTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RestCtrl-MIB::ordersTable is subid 4 of restCtrl.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.12619.4, length: 8
*/


    int ordersTable_init_data(ordersTable_registration * ordersTable_reg);


    /*
     * TODO:180:o: Review ordersTable cache timeout.
     * The number of seconds before the cache times out
     */
#define ORDERSTABLE_CACHE_TIMEOUT   60

void ordersTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
void ordersTable_container_shutdown(netsnmp_container *container_ptr);

int ordersTable_container_load(netsnmp_container *container);
void ordersTable_container_free(netsnmp_container *container);

int ordersTable_cache_load(netsnmp_container *container);
void ordersTable_cache_free(netsnmp_container *container);

    int ordersTable_row_prep( ordersTable_rowreq_ctx *rowreq_ctx);



#ifdef __cplusplus
}
#endif

#endif /* ORDERSTABLE_DATA_ACCESS_H */
