/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
#ifndef ORDERSTABLE_H
#define ORDERSTABLE_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup misc misc: Miscellaneous routines
 *
 * @{
 */
#include <net-snmp/library/asn1.h>

/* other required module components */
    /* *INDENT-OFF*  */
config_add_mib(RestCtrl-MIB)
config_require(RestCtrl-MIB/ordersTable/ordersTable_interface)
config_require(RestCtrl-MIB/ordersTable/ordersTable_data_access)
config_require(RestCtrl-MIB/ordersTable/ordersTable_data_get)
config_require(RestCtrl-MIB/ordersTable/ordersTable_data_set)
    /* *INDENT-ON*  */

/* OID and column number definitions for ordersTable */
#include "ordersTable_oids.h"

/* enum definions */
#include "ordersTable_enums.h"

/* *********************************************************************
 * function declarations
 */
void init_ordersTable(void);
void shutdown_ordersTable(void);

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table ordersTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RestCtrl-MIB::ordersTable is subid 4 of restCtrl.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.12619.4, length: 8
*/
/* *********************************************************************
 * When you register your mib, you get to provide a generic
 * pointer that will be passed back to you for most of the
 * functions calls.
 *
 * TODO:100:r: Review all context structures
 */
    /*
     * TODO:101:o: |-> Review ordersTable registration context.
     */
typedef netsnmp_data_list ordersTable_registration;

/**********************************************************************/
/*
 * TODO:110:r: |-> Review ordersTable data context structure.
 * This structure is used to represent the data for ordersTable.
 */
/*
 * This structure contains storage for all the columns defined in the
 * ordersTable.
 */
typedef struct ordersTable_data_s {
    
        /*
         * item(2)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/R/d/h
         */
   long   item;
    
        /*
         * table(3)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/R/d/h
         */
   long   table;
    
        /*
         * status(4)/INTEGER/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h
         */
   u_long   status;
    
} ordersTable_data;


/*
 * TODO:120:r: |-> Review ordersTable mib index.
 * This structure is used to represent the index for ordersTable.
 */
typedef struct ordersTable_mib_index_s {

        /*
         * ordersIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/R/d/h
         */
   long   ordersIndex;


} ordersTable_mib_index;

    /*
     * TODO:121:r: |   |-> Review ordersTable max index length.
     * If you KNOW that your indexes will never exceed a certain
     * length, update this macro to that length.
*/
#define MAX_ordersTable_IDX_LEN     1


/* *********************************************************************
 * TODO:130:o: |-> Review ordersTable Row request (rowreq) context.
 * When your functions are called, you will be passed a
 * ordersTable_rowreq_ctx pointer.
 */
typedef struct ordersTable_rowreq_ctx_s {

    /** this must be first for container compare to work */
    netsnmp_index        oid_idx;
    oid                  oid_tmp[MAX_ordersTable_IDX_LEN];
    
    ordersTable_mib_index        tbl_idx;
    
    ordersTable_data              data;

    /*
     * flags per row. Currently, the first (lower) 8 bits are reserved
     * for the user. See mfd.h for other flags.
     */
    u_int                       rowreq_flags;

    /*
     * TODO:131:o: |   |-> Add useful data to ordersTable rowreq context.
     */
    
    /*
     * storage for future expansion
     */
    netsnmp_data_list             *ordersTable_data_list;

} ordersTable_rowreq_ctx;

typedef struct ordersTable_ref_rowreq_ctx_s {
    ordersTable_rowreq_ctx *rowreq_ctx;
} ordersTable_ref_rowreq_ctx;

/* *********************************************************************
 * function prototypes
 */
    int ordersTable_pre_request(ordersTable_registration * user_context);
    int ordersTable_post_request(ordersTable_registration * user_context,
        int rc);

    int ordersTable_rowreq_ctx_init(ordersTable_rowreq_ctx *rowreq_ctx,
                                   void *user_init_ctx);
    void ordersTable_rowreq_ctx_cleanup(ordersTable_rowreq_ctx *rowreq_ctx);


    ordersTable_rowreq_ctx *
                  ordersTable_row_find_by_mib_index(ordersTable_mib_index *mib_idx);

extern const oid ordersTable_oid[];
extern const int ordersTable_oid_size;


#include "ordersTable_interface.h"
#include "ordersTable_data_access.h"
#include "ordersTable_data_get.h"
#include "ordersTable_data_set.h"

/*
 * DUMMY markers, ignore
 *
 * TODO:099:x: *************************************************************
 * TODO:199:x: *************************************************************
 * TODO:299:x: *************************************************************
 * TODO:399:x: *************************************************************
 * TODO:499:x: *************************************************************
 */

#ifdef __cplusplus
}
#endif

#endif /* ORDERSTABLE_H */
/** @} */
