/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef ORDERSTABLE_INTERFACE_H
#define ORDERSTABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "ordersTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _ordersTable_initialize_interface(ordersTable_registration * user_ctx,
                                    u_long flags);
void _ordersTable_shutdown_interface(ordersTable_registration * user_ctx);

ordersTable_registration *
ordersTable_registration_get( void );

ordersTable_registration *
ordersTable_registration_set( ordersTable_registration * newreg );

netsnmp_container *ordersTable_container_get( void );
int ordersTable_container_size( void );

    ordersTable_rowreq_ctx * ordersTable_allocate_rowreq_ctx(void *);
void ordersTable_release_rowreq_ctx(ordersTable_rowreq_ctx *rowreq_ctx);

int ordersTable_index_to_oid(netsnmp_index *oid_idx,
                            ordersTable_mib_index *mib_idx);
int ordersTable_index_from_oid(netsnmp_index *oid_idx,
                              ordersTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void ordersTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* ORDERSTABLE_INTERFACE_H */
/** @} */
