/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 *
 * $Id:$
 */
#ifndef ORDERSTABLE_OIDS_H
#define ORDERSTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table ordersTable */
#define ORDERSTABLE_OID              1,3,6,1,4,1,12619,4


#define COLUMN_ORDERSINDEX         1
    
#define COLUMN_ITEM         2
    
#define COLUMN_TABLE         3
    
#define COLUMN_STATUS         4
    

#define ORDERSTABLE_MIN_COL   COLUMN_ORDERSINDEX
#define ORDERSTABLE_MAX_COL   COLUMN_STATUS
    


#ifdef __cplusplus
}
#endif

#endif /* ORDERSTABLE_OIDS_H */
