/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "ordersTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement ordersTable get routines.
 * TODO:240:M: Implement ordersTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table ordersTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RestCtrl-MIB::ordersTable is subid 4 of restCtrl.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.12619.4, length: 8
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement ordersTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param ordersIndex_val
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
ordersTable_indexes_set_tbl_idx(ordersTable_mib_index *tbl_idx, long ordersIndex_val)
{
    DEBUGMSGTL(("verbose:ordersTable:ordersTable_indexes_set_tbl_idx","called\n"));

    /* ordersIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/R/d/h */
    tbl_idx->ordersIndex = ordersIndex_val;
    

    return MFD_SUCCESS;
} /* ordersTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
ordersTable_indexes_set(ordersTable_rowreq_ctx *rowreq_ctx, long ordersIndex_val)
{
    DEBUGMSGTL(("verbose:ordersTable:ordersTable_indexes_set","called\n"));

    if(MFD_SUCCESS != ordersTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , ordersIndex_val
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != ordersTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* ordersTable_indexes_set */


/*---------------------------------------------------------------------
 * RestCtrl-MIB::ordersEntry.item
 * item is subid 2 of ordersEntry.
 * Its status is Mandatory, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.12619.4.1.2
 * Description:
Item do cardapio pedido
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *
 * Ranges:  1 - 2147483647;
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the item data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param item_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
item_get( ordersTable_rowreq_ctx *rowreq_ctx, long * item_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != item_val_ptr );


    DEBUGMSGTL(("verbose:ordersTable:item_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the item data.
 * copy (* item_val_ptr ) from rowreq_ctx->data
 */
    (* item_val_ptr ) = rowreq_ctx->data.item;

    return MFD_SUCCESS;
} /* item_get */

/*---------------------------------------------------------------------
 * RestCtrl-MIB::ordersEntry.table
 * table is subid 3 of ordersEntry.
 * Its status is Mandatory, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.12619.4.1.3
 * Description:
Numera da mesa que fez o pedido
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *
 * Ranges:  1 - 2147483647;
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the table data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param table_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
table_get( ordersTable_rowreq_ctx *rowreq_ctx, long * table_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != table_val_ptr );


    DEBUGMSGTL(("verbose:ordersTable:table_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the table data.
 * copy (* table_val_ptr ) from rowreq_ctx->data
 */
    (* table_val_ptr ) = rowreq_ctx->data.table;

    return MFD_SUCCESS;
} /* table_get */

/*---------------------------------------------------------------------
 * RestCtrl-MIB::mesasEntry.status
 * status is subid 4 of mesasEntry.
 * Its status is Mandatory, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.12619.3.1.4
 * Description:
Status atual da mesa
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 * Enum range: 2/8. Values:  livre(0), ocupada(1), indisponivel(2)
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the status data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param status_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
status_get( ordersTable_rowreq_ctx *rowreq_ctx, u_long * status_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != status_val_ptr );


    DEBUGMSGTL(("verbose:ordersTable:status_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the status data.
 * copy (* status_val_ptr ) from rowreq_ctx->data
 */
    (* status_val_ptr ) = rowreq_ctx->data.status;

    return MFD_SUCCESS;
} /* status_get */



/** @} */
