/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef STATUS_H
#define STATUS_H

/* function declarations */
void init_status(void);
Netsnmp_Node_Handler handle_status;

#endif /* STATUS_H */
